### PR TITLE
Fix typo in Serban Iorga's email

### PR DESCRIPTION
**Pull request by stefannita01**
## Reason for This PR

There was a typo in Serban Iorga's email.

## Description of Changes

I have fixed the typo in Serban Iorga's email.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [ ] All commits in this PR are signed (`git commit -s`).
- [x] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided.
- [x] The description of changes is clear and encompassing.
- [x] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [x] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [x] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [x] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.
- [x] Either no new `unsafe` code has been added, or, the newly added `unsafe`
      code is unavoidable and properly documented.

### CODE REVIEW

**Comment by lauralt** [comment]
@stefannita01 Please, sign your commit: `git commit -s --amend`.

**Comment by stefannita01** [comment]
> @stefannita01 Please, sign your commit: `git commit -s --amend`.

Hello Laura, 

I believe my commit is in fact signed. There's a green "Verified" card next to it, which on hover informs me that it has been signed with GPG key 4AEE18F83AFDEB23. I didn't tick the checkbox in the Pull Request comment because I wasn't sure at the time. Let me know if further steps need to be taken.

**Comment by serban300** [comment]
Thanks for the fix. The commit is indeed signed, but you also need to add a signout line in the commit message. You can do this using the command that Laura provided: `git commit -s --amend`.

**Comment by serban300** [comment]
Hi @stefannita01 . Could you sign out your commit so we can merge this PR ? Thanks !

**Comment by stefannita01** [comment]
> Hi @stefannita01 . Could you sign out your commit so we can merge this PR ? Thanks !

Sorry it took forever. I believe it's good to go now. Thanks.

**Comment by serban300** [comment]
@stefannita01 yes, now it's signed out. Thanks !

Sorry, could you also squash your commits into one please ? Right now there are 4. And Also could you move the sign out line after the commit description? 

Right now it's 
```
Signed-off-by: Stefan Nita <stefannita01@gmail.com>

Fixed typo in Serban Iorga's email
```

Please change it to
```
Fixed typo in Serban Iorga's email

Signed-off-by: Stefan Nita <stefannita01@gmail.com>
```

**Comment by serban300** [comment]
I'm not sure what happened but I see that there are 8 commits now :)

You can squash them by doing `git rebse -i upstream/master` and then marking all but the first commit with `fixup`. Then do a `git push -f`.

@stefannita01 will you do that please ? If not I can try to do it and force push into your branch. Let me know if you need any help with this.

**Comment by lauralt** [comment]
There is a typo in the commit title: `maintaners.md` -> `maintainers.md`.

**Comment by stefannita01** [comment]
> I'm not sure what happened but I see that there are 8 commits now :)
> 
> You can squash them by doing `git rebse -i upstream/master` and then marking all but the first commit with `fixup`. Then do a `git push -f`.
> 
> @stefannita01 will you do that please ? If not I can try to do it and force push into your branch. Let me know if you need any help with this.

Yes, I had some issues figuring out how to squash the commits last nights and I couldn't get to my PC or laptop today until now. I see you guys did that already. Sorry for the headaches for such a simple commit.

Also, poetic how there's now a typo in the commit title. While I am somewhat of a specialist in fixing typos, I am clearly nowhere near as well-versed in the subtleties of git, so I think it's best I don't get involved there...

**Pull request merged**
