### PR TITLE
accumulated dependabot PRs until 2023-06-22

### PR DESCRIPTION
**Pull request by zulinx86**
## Changes

- Cherry-picks dependabot PRs created util 2023-06-22.

## Reason

...

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- ~~[ ] If a specific issue led to this PR, this PR closes the issue.~~
- [x] The description of changes is clear and encompassing.
- ~~[ ] Any required documentation changes (code and docs) are included in this PR.~~
- ~~[ ] API changes follow the [Runbook for Firecracker API changes][2].~~
- ~~[ ] User-facing changes are mentioned in `CHANGELOG.md`.~~
- [x] All added/changed functionality is tested.
- ~~[ ] New `TODO`s link to an issue.~~
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [x] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by roypat — APPROVED** [review]

**Review by pb8o — DISMISSED** [review]

**Comment by zulinx86** [comment]
removed the commit that updates Cargo.lock files by running `cargo update` manually.

**Review by roypat — DISMISSED** [review]

**Comment by zulinx86** [comment]
> dirty lock files :(

yeah, I'm taking a look.

**Comment by zulinx86** [comment]
The root cause of the no_dirty_cargo_locks_check failure was that dependabot PRs don't update ./tests/integration_tests/security/demo_seccomp/Cargo.lock.

**Comment by roypat** [comment]
> The root cause of the no_dirty_cargo_locks_check failure was that dependabot PRs don't update ./tests/integration_tests/security/demo_seccomp/Cargo.lock.

oh, interesting! Seems like we have to register those crates to the config: https://github.com/dependabot/dependabot-core/issues/2824

**Comment by zulinx86** [comment]
> Seems like we have to register those crates to the config: https://github.com/dependabot/dependabot-core/issues/2824

When we register them, will we get multiple PRs for each?

**Comment by zulinx86** [comment]
Any way, will handle it in another PR since it's out of scope of this PR.
Now the no_dirty_cargo_locks_check passed with my manual update by running `cargo update -p <package>`.

**Review by roypat — APPROVED** [review]

**Comment by roypat** [comment]
> > Seems like we have to register those crates to the config: [dependabot/dependabot-core#2824](https://github.com/dependabot/dependabot-core/issues/2824)
> 
> When we register them, will we get multiple PRs for each package update?

I actually dont know :thinking:

**Review by kalyazin — APPROVED** [review]

**Pull request merged**
