### PR TITLE
Update network-setup.md

### PR DESCRIPTION
**Pull request by soma115**
eth0 should be up before route add.

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by soma115** [comment]
I'm sorry, I'm not able to follow instructions in my current environment. 
The point of proposed change is that this part of instruction will fail without command I've added.

I agree with license terms and conditions.

**Comment by andreeaflorescu** [comment]
Each git commit has to have the following text in the commit description: "Signed-off-by: Name <email@address.com>". Take a look at other commits to see how it looks. This is one of the latest commit on master: https://github.com/firecracker-microvm/firecracker/commit/11e19ba050d87d358eea321d751a01690a5f2e73.

The signed-off is an acknowledgement of the license. As Alexandra said, you will have to amend your commit to get the signing appended to your commit message. The easiest way to do this is to use the following lines:
```bash
# Amend commit to sign it
git commit --amend -s --no-edit  
# Update remote branch
git push -f
```

**Comment by andreeaflorescu** [comment]
@soma115 can you please update the commit message so we can merge this PR?

**Comment by dianpopa** [comment]
Closing this due to inactivity. @soma115 feel free to reopen this as soon as you can resume work on this.

**Pull request closed without merging**
