### PR TITLE
Audit seccomp allowlist

### PR DESCRIPTION
**Pull request by alindima**
Audit seccomp allowlist. Remove unneeded syscalls and tighten allowed conditions.

Signed-off-by: alindima alindima@amazon.com

## Reason for This PR

The seccomp filters needed some auditing to tighten security even further and improve maintainability.
Some syscalls or parameters are no longer needed and some are used only before installing the filters.

## Description of Changes

* Removed some allowed syscalls and seccomp conditions.
* Added some more architecture-specific rules.
* Restricted allowed parameters even more.
* Modified a `fcntl` parameter type to be `DWORD`
* Added descriptive comments where relevant.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by alindima** [comment]
This PR is made on a feature branch. Even though I can merge it without any reviews, I would like to have at least two.
This is because the code will likely go to some clients in an experimental binary and we need to be extra careful about the code.

**Comment by acatangiu** [comment]
Feature branches need to be gated by reviews as well. I will show you how to enable branch protections.

**Comment by dianpopa** [comment]
> This PR is made on a feature branch. Even though I can merge it without any reviews, I would like to have at least two.
> This is because the code will likely go to some clients in an experimental binary and we need to be extra careful about the code.

If you rename your branch to something like "feature/*", you will get the 2 approval branch protection rule by default.

**Comment by alindima** [comment]
> > This PR is made on a feature branch. Even though I can merge it without any reviews, I would like to have at least two.
> > This is because the code will likely go to some clients in an experimental binary and we need to be extra careful about the code.
> 
> If you rename your branch to something like "feature/*", you will get the 2 approval branch protection rule by default.

@dianpopa It seems that, according to our latest branching strategy, we decided to name feature branches `firecracker-featureName`

**Comment by dianpopa** [comment]
> > > This PR is made on a feature branch. Even though I can merge it without any reviews, I would like to have at least two.
> > > This is because the code will likely go to some clients in an experimental binary and we need to be extra careful about the code.
> > 
> > 
> > If you rename your branch to something like "feature/*", you will get the 2 approval branch protection rule by default.
> 
> @dianpopa It seems that, according to our latest branching strategy, we decided to name feature branches `firecracker-featureName`

oh, ok, I see, so we will be having `firecracker-microvm/firecracker/fircracker-feature` branches, :(. In that case we should also add a rule for this ugly naming in our branch protection.

**Comment by alindima** [comment]
I will delete the branch and fall back to the previous naming convention.

**Pull request closed without merging**
