### PR TITLE
seccomp: code and docs adjustments

### PR DESCRIPTION
**Pull request by KarthikNedunchezhiyan**
## Description of Changes

This PR includes:

- Changed level representation of seccomp from u32 to u8.
- Some code and docs adjustments.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided.
- [x] The description of changes is clear and encompassing.
- [x] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [x] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [x] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [x] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.
- [x] Either no new `unsafe` code has been added, or, the newly added `unsafe`
      code is unavoidable and properly documented.

### CODE REVIEW

**Comment by KarthikNedunchezhiyan** [comment]
@aghecenco I have also changed some other codes in [52da735](https://github.com/firecracker-microvm/firecracker/commit/52da735d31811ff2675a95d2a2a093a3a826d105) other than modifying of level representation. it that ok 🙂?

**Comment by aghecenco** [comment]
@KarthikNedunchezhiyan that's fine with me :+1:

**Comment by KarthikNedunchezhiyan** [comment]
@aghecenco applied changes as like you suggested 🙂.

**Comment by KarthikNedunchezhiyan** [comment]
@aghecenco please take a another look 🙂.

**Pull request merged**
