### PR TITLE
kernel-config: Remove kernel modules from config

### PR DESCRIPTION
**Pull request by rn**
Firecracker is booting with 'nomodules' so there is no
need to have any modules configured in the kernel config.

The new kernel config is derived from the existing one
by running  a script, replacing all:
```
  CONFIG_<FOO>=m
```
with
```
  # CONFIG_<FOO> is not set
```
and then run 'make oldconfig' using the upstream 4.14.72
kernel (as used before).

Signed-off-by: Rolf Neugebauer <rn@rneugeba.io>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by acatangiu** [comment]
@rn did you happen to run the integration tests suit with this version of the generated kernel image?

**Comment by rn** [comment]
@acatangiu I haven't run the tests but booted the new kernel on firecracker. What are the runes to run the tests with a custom kernel?

**Comment by dhrgit** [comment]
@rn Ok, bear with me (our testing system is a bit overdue for an overhaul):
- When the integration tests are run (either via pytest or devtool), the test images are downloaded from S3. When using `devtool test`, the images are also cached locally under `build/img`.
- Under `build/img` there will be a few directories, each dir holding a test configuration
- Each test config has a kernel (`vmlinux.bin`), a rootfs, and some other stuff
- The kernel should be the same in every test config, except for `ubuntu_with_partuuid`, which requires a kernel capable of receiving a partuuid cmdline parameter

So, to run the tests with a new kernel, you can
- replace all the `vmlinux.bin` files under `build/img` (except for the one under `ubuntu_with_partuuid`) with your new kernel
- and then run `devtool test`

**Comment by rn** [comment]
Finally got around running the tests with the existing kernel and the new kernel config. With the exiting kernel, downloaded from S3 I get on error:
```
_________________________________________________________ test_startup_time[ubuntu] __________________________________________________________
integration_tests/performance/test_process_startup_time.py:49: in test_startup_time
    assert cpu_startup_time_us <= MAX_STARTUP_TIME_CPU_US
E   assert 104704 <= 8000
```

replacing the downloaded `vmlinux.bin` with a kernel compiled from the new config, I get three failures:
```
_______________________________________________________________ test_gnutests ________________________________________________________________
integration_tests/build/test_unittests.py:44: in test_gnutests
    check=True
/usr/lib/python3.6/subprocess.py:418: in run
    output=stdout, stderr=stderr)
E   subprocess.CalledProcessError: Command 'CARGO_TARGET_DIR=/tmp/firecracker_test_session/firecracker_binaries/test RUST_TEST_THREADS=1 RUST_BACKTRACE=1 cargo test --target x86_64-unknown-linux-gnu --all --no-fail-fast' returned non-zero exit status 101.
__________________________________________________ test_partuuid_boot[ubuntu_with_partuuid] __________________________________________________
integration_tests/functional/test_drives.py:134: in test_partuuid_boot
    _check_drives(test_microvm, assert_dict, keys_array)
integration_tests/functional/test_drives.py:254: in _check_drives
    ssh_connection = net_tools.SSHConnection(test_microvm.ssh_config)
host_tools/network.py:52: in __init__
    self.initial_connect(ssh_config)
host_tools/network.py:69: in initial_connect
    max_delay=32
/usr/local/lib/python3.6/dist-packages/retry/api.py:101: in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
/usr/local/lib/python3.6/dist-packages/retry/api.py:33: in __retry_internal
    return f()
/usr/local/lib/python3.6/dist-packages/paramiko/client.py:343: in connect
    retry_on_signal(lambda: sock.connect(addr))
/usr/local/lib/python3.6/dist-packages/paramiko/util.py:280: in retry_on_signal
    return function()
/usr/local/lib/python3.6/dist-packages/paramiko/client.py:343: in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
E   TimeoutError: [Errno 110] Connection timed out
_________________________________________________________ test_startup_time[ubuntu] __________________________________________________________
integration_tests/performance/test_process_startup_time.py:49: in test_startup_time
    assert cpu_startup_time_us <= MAX_STARTUP_TIME_CPU_US
E   assert 102167 <= 8000
```

I'm not too familiar with the test infrastructure, but is there a way to get more detailed log, in particular the VM serial console on the failing test? And can I re-run just the failing test or something?

**Comment by dhrgit** [comment]
@rn 
There are a few known problems with the integration test suite. You've stumbled across one of them now: test_startup_time sometimes behaves rather weird and fails on desktop machines; this is tracked by #873 .

Another problem is the inability to efficiently debug a failing test. Although you can run just a particular test:

```bash
# All arguments after -- are passed through to pytest
devtool test -- tests/integration_tests/functional/test_drives.py::test_partuuid_boot

# Alternatively:
devtool shell -p
cd tests && pytest tests/integration_tests/functional/test_drives.py::test_partuuid_boot
```

it will take a while, since it will have to rebuild the binaries from scratch each time. That's about 100s on a good desktop.

Another one: the tests are run with the guest console disabled and the overall output is messy, so not quite as helpful as it could be.

Back to the remaining two tests that are failing:
- `test_gnutests`: all unit tests, run on the glibc build. You can find which unit test is failing by scrolling up through that messy output, looking for the failed unit test. This should be unaffected by your kernel change. Are you running the tests outside our container?
- `test_partuuid_boot`: tests booting with `root=PARTUUID=`, instead of `root=/dev/vda`. It is the only test config that uses its own kernel (under `ubuntu_with_partuuid/kernel/vmlinux.bin`), so it will fail when run with this kernel. Not sure why it isn't working with the default kernel, since looking at the kernel code, `root=PARTUUID=` should be supported by all kernels with `CONFIG_BLOCK=y` - there is something I'm missing here. Haven't deep-dived into it, since booting this way is not really used by anyone, and I believe we just need to take the time and remove this option from Firecracker altogether.

**Comment by andreeaflorescu** [comment]
If you do not want to wait every time to build the firecracker binaries, you can hardcode `path_to_binaries` variable from `get_firecracker_binaries` in `tests/host_tools/cargo_build.py`. At some point we should have this configurable so it is easier to run individual tests fast on a development machine.

**Comment by andreeaflorescu** [comment]
If you do not want to wait every time to build the firecracker binaries, you can hardcode `path_to_binaries` variable from `get_firecracker_binaries` in `tests/host_tools/cargo_build.py`. At some point we should have this configurable so it is easier to run individual tests fast on a development machine.

**Comment by andreeaflorescu** [comment]
What are the next steps to get this merged?

**Comment by rn** [comment]
Unfortunately, I did not have time to debug the failure further and I won't have time for another week or two. If you don't want to keep this open till then, feel free to close it for now and I'll pick it up when I have time again.

**Comment by dhrgit** [comment]
Ran the tests with the herein kernel config and everything looks good.

**Comment by alakesh** [comment]
The changes look good. I will try to build amazon linux kernel with these changes internally and do some basic sanity.

**Comment by acatangiu** [comment]
@alakesh Any luck with validating the amazon linux kernel with these changes?

**Comment by alakesh** [comment]
I have internally verified that with removal of module configs, there is no regression. Changes look good.

**Pull request merged**
