### PR TITLE
kernel loader: replace struct_util with ByteValued

### PR DESCRIPTION
**Pull request by yichen-zhang-dev**
Per issue #1683, replace read_struct and read_struct_slice with ByteValued, similar to the change made in https://github.com/rust-vmm/linux-loader/pull/26/files.

Co-authored-by: Kevin Guo <kev.guo123@gmail.com>
Co-authored-by: Preston Sundar <sundar.preston.789@gmail.com>
Signed-off-by: Yichen Zhang <jakezhang2020@gmail.com>

## Reason for This PR
issue #1683

## Description of Changes

Replace read_struct and read_struct_slice with ByteValued in mod.rs, similar to the change made in https://github.com/rust-vmm/linux-loader/pull/26/files.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Review by georgepisaltu — COMMENTED** [review]
Hi @yichen-zhang-dev , thanks for your contribution!

While the changes look ok, it seems there is a unit test that fails on aarch64. Also, your commit needs to respect the 50/72 rule, and the commit description breaks that at the moment.

**Review by serban300 — COMMENTED** [review]
Can we delete the `utils::structs` module now ? Is it still needed ?

**Comment by georgepisaltu** [comment]
Hi, @yichen-zhang-dev!

Are you still interested in merging this PR?

**Comment by dianpopa** [comment]
@georgepisaltu @serban300 the PR is ready for another review! Thanks!

**Review by georgepisaltu — COMMENTED** [review]
LGTM! Please also resolve the conflicts in `test_coverage.py`.

**Review by serban300 — APPROVED** [review]

**Review by georgepisaltu — APPROVED** [review]

**Review by serban300 — APPROVED** [review]

**Pull request merged**
