### PR TITLE
rustfmt: format doc comments

### LINKED ISSUE #1321: Documentation code does not get rustfmt'd by default
There is a solution to this. Checkout `format_code_in_doc_comments` in https://github.com/rust-lang/rustfmt/blob/master/Configurations.md but it is not stable yet. We should poll on that and bring it in Firecracker once stable.

### PR DESCRIPTION
**Pull request by dianpopa**
# Reason for This PR

Fixes #1321.

## Description of Changes

`[Author TODO: add description of changes.]`

- [ ] This functionality can be added in [`rust-vmm`][1].

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The issue which led to this PR has a clear conclusion.
- [x] This PR follows the solution outlined in the related issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes follow the [Runbook for Firecracker API changes][2].
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

[1]: https://github.com/rust-vmm
[2]: ../docs/api-change-runbook.md

### CODE REVIEW

**Review by georgepisaltu — APPROVED** [review]
Nice!

**Comment by alindima** [comment]
I see that this is still considered an unstable feature. Do we want to merge it as-is and later rollback if we see stability issues? @dianpopa

**Comment by dianpopa** [comment]
> I see that this is still considered an unstable feature. Do we want to merge it as-is and later rollback if we see stability issues? @dianpopa

Unstable features are not merged in stable branches (which we are using). Where did you see that this is still unstable?

**Comment by alindima** [comment]
> > I see that this is still considered an unstable feature. Do we want to merge it as-is and later rollback if we see stability issues? @dianpopa
> 
> Unstable features are not merged in stable branches (which we are using). Where did you see that this is still unstable?

I was referring to the rustfmt docs: https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#format_code_in_doc_comments

But it seems that the docs are outdated

**Pull request merged**
