### PR TITLE
Glibc support for Firecracker

### PR DESCRIPTION
**Pull request by aliguori**
This allows the standard rust toolchain to work out of the box.  This makes Firecracker much more accessible for a typical user while still retaining the ability to build for musl.

### CODE REVIEW

**Comment by dhrgit** [comment]
> Do we really need to depend on libbacktrace?

We currently use a stack trace lib to dump the trace into the log, in case of an unexpected panic.

We couldn't find a rust-native alternative to libbacktrace. And, if it's C, chances are GCC will generate some of those stack protection calls.

Barring a rust stack trace solution (or a similarly helpful troubleshooting mechanism), these are the options I can think of, in the order of my preference:
- use `devtool` for building
  drawback: requires Docker
- *or* compile libbacktrace with `-N_FORTIFY_SOURCE`
  drawback: need to investigate impact
- *or* default to glibc
  drawbacks:
  - invalidates our static linking, just-works model
  - requires a more relaxed seccomp filter
- *or* don't log stack trace on panic
  drawback: makes troubleshooting considerably more difficult

**Comment by messense** [comment]
> We couldn't find a rust-native alternative to libbacktrace.

FYI, there is [an ongoing effect to replace libbacktrace with a native Rust implementation in rustc](https://github.com/rust-lang/rust/issues/46439)

**Comment by andreeaflorescu** [comment]
+1 for using a rust-native alternative to libbacktrace

**Comment by andreeaflorescu** [comment]
Closing this due to no activity, please re-open if you still want to get it merge.

**Pull request closed without merging**
