### PR TITLE
Remove extern crate, apply clippy lints

### PR DESCRIPTION
**Pull request by damienstanton**
## Reason for This PR

Now that the project has been successfully migrated to 2018 edition, usage of `extern crate` is no longer required. In addition, clippy reports a few instances of unused imports, uneeded `Box`ing, and unneeded clones, and out of date doctest implementations.

## Description of Changes

- Remove all declarations of `extern crate`
- Refactor doctests per clippy to remove `fn main()` and correct imports
- Refactor unneeded imports, and broken macro imports 

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by acatangiu** [comment]
I'm a bit confused. How did the previous "switch to Rust 2018" PR pass clippy test if clippy was reporting issues? 😄

**Comment by damienstanton** [comment]
> I'm a bit confused. How did the previous "switch to Rust 2018" PR pass clippy test if clippy was reporting issues? 😄

Good question! It looks like the additional clippy warnings only appeared after removing the `extern crate` and `#[macro_use]` declarations, which is interesting.

**Comment by damienstanton** [comment]
I will have some more time tomorrow to look into the current `aarch64` build failure. It appears to be a networking error or timeout, some details from the log:
```console
[15981] Command:
['ssh', '-q', '-o', 'ConnectTimeout=1', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/tmp/fctest-34yl2q4s/70bdd7e0-2de1-4655-ac1a-4984f8f789b0/fsfiles/xenial.rootfs.id_rsa', 'root@192.168.0.166', 'workers="";for i in $(seq 1 50); do  (hash=$(cat /tmp/vsock/test.blob | vsock_helper echo 2 5252 | md5sum | cut -f1 -d\\ ) && [[ "$hash" = "d121eddd4e9369f696ea0831fabdb6e2" ]])&   workers="$workers $!";done;for w in $workers; do wait $w || exit -1; done']
[15981] stderr:
socket(): Address family not supported by protocol
```

**Comment by iulianbarbu** [comment]
Have the same issue on #2041 .

**Comment by dianpopa** [comment]
> Have the same issue on #2041 .

Looking into it.

**Pull request merged**
