### PR TITLE
Updated doc for creating rootfs sample: automount sysfs

### PR DESCRIPTION
**Pull request by ishworgurung**
Issue #, if available:

Description of changes:
add `sysfs` to automount upon boot

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dianpopa** [comment]
1. Sign your commit:
git commit --amend -s
2. While ammending your commit, please use a more descriptive messages, something like:
```
Updated doc for creating rootfs sample

Apart from procfs and devfs, sysfs could also get mounted on boot.
```

**Comment by ishworgurung** [comment]
thank you @dianpopa.

I have signed the commit and amended the commit message.

**Comment by serban300** [comment]
@ishworgurung  please squash the commits. I think 1 commit would be enough. 

@dhrgit could you take a look on this change since you wrote this doc ?

**Comment by ishworgurung** [comment]
thank you @serban300. It is a single commit now.

**Comment by dhrgit** [comment]
> @dhrgit could you take a look on this change since you wrote this doc ?

@ishworgurung The change looks OK, but please be a little more verbose in your commit message. This is updating the rootfs creation guide, which is not apparent from that generic commit message.

**Pull request merged**
