### PR TITLE
fixed shell commands in documentation

### PR DESCRIPTION
**Pull request by rchakode**
docs/getting-started.md: fixed example commands with environment variables included between single quote. 
--
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchakode** [comment]
This PR replaces #1161

**Comment by andreeaflorescu** [comment]
@rchakode you need to split the description of your commit message on multiple lines. Each line must have at most 72 characters.

To merge this PR the commit also needs to be signed to acknowledge the Apache-2.0 license. You can do that with the following command:
```git commit --amend --no-edit -s```
and then do a `push -f`

**Comment by rchakode** [comment]
commit updated and signed as indicated.

**Comment by rchakode** [comment]
sorry, I updated the email in the signature to use a personal one :)

**Comment by acatangiu** [comment]
@rchakode please also add:

> By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

to this PR description (just edit your first comment - no need to do anything in `git`)

**Comment by rchakode** [comment]
> @rchakode please also add:
> 
> > By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> 
> to this PR description (just edit your first comment - no need to do anything in `git`)

Done.

**Comment by rchakode** [comment]
hi,
I'm seeing that this PR was assigned to me, is there any additional things I should do ?

Regards,
R.

**Comment by andreeaflorescu** [comment]
@rchakode nop, all is good. We are having some problems with our CI at the moment. Once we fixed them we will merge your PR.

**Pull request merged**
