### PR TITLE
Cleanup unused imports

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by serban300** [comment]
@gliptak some of those imports seem to be needed. I see that the build fails with these changes.

**Comment by serban300** [comment]
Maybe those dependencies can be removed only for aarch64. So it would look something like this:

```
use sys_util::EventFd
#[cfg(target_arch = "x86_64")]
use sys_util::Terminal;
```

**Comment by dianpopa** [comment]
Yes, those unused imports apply only to aarch64 code. There is already an issue #1007 for adding clippy integration test fo aarch64. In order to make clippy test successful we also need to get rid of warnings.

**Comment by gliptak** [comment]
@serban300  @dianpopa thank you for the pointers. The compile seems to be now corrected, but there are still build failures. Could you help me understand if/how those are related?

**Comment by serban300** [comment]
@gliptak the failures are definitely related to your changes. I see that the test that failed is 

`cargo fmt --all -- --check`

You can try to run the command and fix the issues that are reported.

**Comment by gliptak** [comment]
@serban300 yep, Rust is particular on import ordering. The builds are green

**Pull request merged**
