### PR TITLE
[RFC] InitialVMMConfig to configure and auto-start MicroVM

### PR DESCRIPTION
**Pull request by monsterzz**
It's quite handy to configure and start microvm using only single config file and one command. Something similar was requested in #343 

If someone is interested in this approach I would continue working on it (at least there should be test case for initialization w/ and w/o initial config).

Signed-off-by: Gleb Borisov <borisov.gleb@gmail.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by raduweiss** [comment]
@monsterzz thanks for the PR! A one-off config option is something that I think our customers will love.

This gets more tricky when you run with the `jailer`: among other things, it will do a `chroot` and then exec into `firecracker`. So, the `jailer` will need to copy/move the config file into the filesystem that's visible to `firecracker` after the exec.

Since not all microVMs on the host are the same, I think that leaves the on-host orchestrator with 2 options:

- create/pick a config file for each one and pass it to the `jailer` as an argument;
- have a base config for each one and pass it to the `jailer` as an argument, and then send some API commands to configure what's different.

I don't think users will particularly like either of these options.

Another way to go would be to add an API command that configures more/all resources. What do you think about that path?

**Comment by monsterzz** [comment]
Didn't thought about `jailer` yesterday :(

It really looks complicated, especially when I think about kernel and rootfs blobs, which also should be copied by jailer inside chroot. Anyway, I think that this way still looks promising because client could generate configuration file and just run jailer/firecracker with few lines of code without waiting for socket availability, sending any requests and parsing responses.

Single API call for VMM configuration could be easily done using my InitialVMMConfig structure (I think it should be renamed in this case). I will dig into API layer and check what should be done to support this case (still novice in Rust).

**Comment by raduweiss** [comment]
The other thing is that there can API actions that are done /after/ the microVM is booted.

Right now the big example is the drive rescan, which is basically a sort of block device hot-plug without having ACPI support. Some flexibility in updating the contents of the block device after boot is very useful thing to have in real production scenarios.

But, we may see more post-boot APIs in the future. For example, if we ever support some form of "freeze/thaw" capabilities. So clients won't be able to forgo the API.

**Comment by acatangiu** [comment]
@monsterzz as per the conversation I'm closing this PR. Feel free to reopen if you decide to contribute to the single API path 😃

**Pull request closed without merging**
