### PR TITLE
build: `-Ccodegen-units=1`

### PR DESCRIPTION
**Pull request by JonathanWoollett-Light**
Issue: https://github.com/firecracker-microvm/firecracker/issues/2699

## Changes

Yields a 180224 bytes decrease in the binary size.

## Reason

Adds `-Ccodegen-units=1` to improve performance and decrease binary size.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] API changes follow the [Runbook for Firecracker API changes][2].
- [x] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [x] New `TODO`s link to an issue.
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [x] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by kalyazin — APPROVED** [review]

**Comment by roypat** [comment]
Did you measure the impact on compile time? The [docs](https://doc.rust-lang.org/nightly/rustc/codegen-options/index.html#codegen-units say
> When a crate is split into multiple codegen units, LLVM is able to process them in parallel. Increasing parallelism may speed up compile times, but may also produce slower code. Setting this to 1 may improve the performance of generated code, but may be slower to compile.

If its bad we might only want to enable it for release builds so that local testing builds remain fast

**Comment by kalyazin** [comment]
>If its bad we might only want to enable it for release builds so that local testing builds remain fast

I would prefer for both builds to use the same setting to avoid surprises.

**Comment by JonathanWoollett-Light** [comment]
> Did you measure the impact on compile time?

The compile time is fast with and without the option, there is no noticeable difference.

**Comment by roypat** [comment]
> > If its bad we might only want to enable it for release builds so that local testing builds remain fast
> 
> I would prefer for both builds to use the same setting to avoid surprises.

Our CI only uses release builds anyway, so I don't think there would be any surprises anywhere. But since the impact seems to be minimal, ship it

**Review by roypat — APPROVED** [review]

**Pull request merged**
