### PR TITLE
fix: Exclude CPUID templates on Arm

### PR DESCRIPTION
**Pull request by JonathanWoollett-Light**
## Changes

Apply `#[cfg(target_arch = "x86_64")]` to CPUID template to avoid compiling them on Arm.

## Reason

Minimizes negative impact on Arm coverage.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] API changes follow the [Runbook for Firecracker API changes][2].
- [x] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [x] New `TODO`s link to an issue.
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality can be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md

### CODE REVIEW

**Review by kalyazin — COMMENTED** [review]
Is there a way to exclude the entire crate from non-x86 builds altogether?

**Comment by JonathanWoollett-Light** [comment]
> Is there a way to exclude the entire crate from non-x86 builds altogether?

By default it builds every crate in the workspace. 

There is an `--exclude` argument on build so we could conditionally exclude this crate when on `aarch64` with some extra Python code in `test_coverage`. I personally dislike this approach.

**Comment by kalyazin** [comment]
> > Is there a way to exclude the entire crate from non-x86 builds altogether?
> 
> By default it builds every crate in the workspace.
> 
> There is an `--exclude` argument on build so we could conditionally exclude this crate when on `aarch64` with some extra Python code in `test_coverage`. I personally dislike this approach that adds complexity to the test itself.

That's fair enough. My only concern is if we ever need to add something to the ```src/cpuid-templates/src/lib.rs```, we'll have to keep in mind adding ```#[cfg(target_arch = "x86_64")]```, which is not very ergonomic.

**Comment by JonathanWoollett-Light** [comment]
> > > Is there a way to exclude the entire crate from non-x86 builds altogether?
> > 
> > 
> > By default it builds every crate in the workspace.
> > There is an `--exclude` argument on build so we could conditionally exclude this crate when on `aarch64` with some extra Python code in `test_coverage`. I personally dislike this approach that adds complexity to the test itself.
> 
> That's fair enough. My only concern is if we ever need to add something to the `src/cpuid-templates/src/lib.rs`, we'll have to keep in mind adding `#[cfg(target_arch = "x86_64")]`, which is not very ergonomic.

I agree this is non-optimal. I think this is the common case where many of our crates should really be modules.

At the time I was trying to segregate functionality to make it more readable. Perhaps now a better solution here would be moving `cpuid-templates` into a module under `src/vmm/src/vstate/vcpu/x86_64/cpuid_templates.rs` what are your thoughts on this?

**Comment by kalyazin** [comment]
> > > > Is there a way to exclude the entire crate from non-x86 builds altogether?
> > > 
> > > 
> > > By default it builds every crate in the workspace.
> > > There is an `--exclude` argument on build so we could conditionally exclude this crate when on `aarch64` with some extra Python code in `test_coverage`. I personally dislike this approach that adds complexity to the test itself.
> > 
> > 
> > That's fair enough. My only concern is if we ever need to add something to the `src/cpuid-templates/src/lib.rs`, we'll have to keep in mind adding `#[cfg(target_arch = "x86_64")]`, which is not very ergonomic.
> 
> I agree this is non-optimal. I think this is the common case where many of our crates should really be modules.
> 
> At the time I was trying to segregate functionality to make it more readable. Perhaps now a better solution here would be moving `cpuid-templates` into a module under `src/vmm/src/vstate/vcpu/x86_64/cpuid_templates.rs` what are your thoughts on this?

That looks sensible to me. At some point we will probably rename to something like cpu_templates, when they also include MSRs. We don't seem to have enough information now on how it is going to be structured though. If you can't see any immediate problems in such evolution, I'm fine with moving like you proposed.

**Review by kalyazin — APPROVED** [review]

**Review by zulinx86 — APPROVED** [review]

**Pull request merged**
