### PR TITLE
 Add instructions to getting-started documentation

### PR DESCRIPTION
**Pull request by RobertDev**
Adds instructions for:
    - Renaming the firecracker binary after downloading
    - Making the firecracker binary executable

Issue #827 , if available:

Description of changes:
This is a small change to the getting-started.md file which adds instructions for renaming the binary once it's downloaded, and subsequently making the binary executable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
Please sign your commit using `git commit --amend -s --no-edit`

**Comment by RobertDev** [comment]
Sure, apologies for the miss on signing I'm new to open source contributing.
Looks like signing creates a new commit. 
-Do you prefer appending the signing commit to the PR branch? 
-Amending the original commit and force pushing (replacing the original commit in the PR branch)? 
-Or appending the signing commit and squashing both commits into one?

**Comment by acatangiu** [comment]
@RobertDev either amend the original commit by signing it `git commit -s --amend` or add another signed commit then squash them together. The end result should be the same and a force push `git push -f` will be necessary either way.

**Comment by RobertDev** [comment]
@acatangiu appreciate the advice, thank you!

**Pull request merged**
