### PR TITLE
Missing c7g baselines

### PR DESCRIPTION
**Pull request by ShadowCurse**
## Changes
Adds missing baselines for c7g.metal

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] API changes follow the [Runbook for Firecracker API changes][2].
- [x] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [x] New `TODO`s link to an issue.
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality can be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by pb8o — DISMISSED** [review]

**Review by zulinx86 — COMMENTED** [review]
Don't we need initrd boot time baseline for c7g.metal?
https://github.com/firecracker-microvm/firecracker/blob/main/tests/integration_tests/performance/test_boottime.py

**Comment by ShadowCurse** [comment]
> Don't we need initrd boot time baseline for c7g.metal? https://github.com/firecracker-microvm/firecracker/blob/main/tests/integration_tests/performance/test_boottime.py

Added those as well

**Comment by zulinx86** [comment]
Can I see the test result?
Or how about merging this into PR #3463?

**Comment by zulinx86** [comment]
> > Can I see the test result? Or how about merging this into PR #3463?
> 
> What do you mean by test results? Results from c7g.metal? If we were to merge this PR into #3463 as you said we would see the results.

Yes, results from c7g.metal. I'd like to check if all the PR tests actually pass on c7g.metal before merging this.
In addition, if we merge these 2 PRs, we don't have to review both, right?

**Comment by ShadowCurse** [comment]
> Yes, results from c7g.metal. I'd like to check if all the PR tests actually pass on c7g.metal before merging this. In addition, if we merge these 2 PRs, we don't have to review both, right?

Well, you wouldn't need to review 2 PRs, but we would need to review 2x code changes...
But yeah, I will talk to @pb8o to merge it into his PR.

**Comment by ShadowCurse** [comment]
This PR was merged with #3463

**Pull request closed without merging**
