### PR TITLE
Ratelimiter API: Correctly return error for invalid fields in PUT/PATCH requests 

### PR DESCRIPTION
**Pull request by pyrito**
## Reason for This PR

Invalid fields in PATCH requests should be failing properly with an error message, not silently. See #1437 for more information.

## Description of Changes

Added serde macro to the RateLimiterConfig.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided.
- [x] The description of changes is clear and encompassing.
- [x] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [x] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [x] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [x] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.
- [x] Either no new `unsafe` code has been added, or, the newly added `unsafe`
      code is unavoidable and properly documented.

### CODE REVIEW

**Comment by pyrito** [comment]
@acatangiu 
I have done as you said: updated the commit message, signed the commit, and added a test case.

**Comment by acatangiu** [comment]
@pyrito In order to be able to tick
> Either the changes in this PR have no user impact, or, the changes in
this PR have user impact and have been added to the CHANGELOG.md file.

you should also add an entry in `CHANGELOG.md` under the `Fixed` section where you should describe the change in behaviour as seen by the user.

Also don't forget to squash your commits as described in my previous comment :)

**Comment by pyrito** [comment]
@acatangiu will get it done soon. I am having some issues just figuring out how to squash the commits because I seemed to have pulled master recently...should have it figured out either today or tomorrow.

**Comment by pyrito** [comment]
Thanks @dianpopa ! @acatangiu everything should be done and ready to merge now!

**Pull request merged**
