### PR TITLE
vmm: Introduce `riscv64` architecture

### PR DESCRIPTION
**Pull request by TimePrinciple**
Introduce `riscv64` architecture.

## Changes

Introduce `riscv64` architecture support for vmm module.

## Reason

Enable firecracker to work on RISC-V 64-bit platforms.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this
  PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet
  [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

______________________________________________________________________

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by zulinx86** [comment]
Hello @TimePrinciple ,
Thank you for opening this PR.

Sorry, but we are not planning to support this feature into Firecracker at least in the near future, because  we don't have RISC-V hardware in our testing infra to test the functionality continuously and we have not received much valid business use cases for it.

If you (or viewers) have a specific use case, could you share it with us? Based on the inputs, we may reconsider its validity :)

Thank you for your understanding.

**Comment by zulinx86** [comment]
Hello,

We are closing this issue for now because it is not currently planned.
We will come back to this PR if we receive enough business use cases for RISC-V support.

Thank you for your effort and understanding.

**Comment by TimePrinciple** [comment]
> Hello,
> 
> We are closing this issue for now because it is not currently planned. We will come back to this PR if we receive enough business use cases for RISC-V support.
> 
> Thank you for your effort and understanding.

Sorry for my late response, I will continue to develop RISC-V architecture support until it is accepted by firecracker team. I wonder would it be a troube to remain opened as a draft :)

**Comment by zulinx86** [comment]
Yes, we can keep this PR opened as a draft :)
We won't be able to merge it into main without valid business use case, but we may be able to merge it into a feature branch.

Thanks.

**Comment by TimePrinciple** [comment]
> Yes, we can keep this PR opened as a draft :) We won't be able to merge it into main without valid business use case, but we may be able to merge it into a feature branch.
> 
> Thanks.

How very kind, that's exactly what I'm expecting at this stage. I will keep developing and updating this work in a feature branch, and I believe this will be picked up one day by main branch when RISC-V is mature enough.

I'm currently working on supporting `rust-vmm` crates on RISC-V, and I will get back to this work when they are finished. And repurpose this PR to another branch by that time :)

**Comment by zulinx86** [comment]
We really appreciate your passion and effort to contribute to Firecracker!
And I really hope that RISC-V gets mature and many cloud vendors adopts it 🚀 
Thanks!

**Comment by TimePrinciple** [comment]
Works migrated to #4819

**Pull request closed without merging**
