### PR TITLE
fix: subtract pre-`run()` execution time from startup time again

### PR DESCRIPTION
**Pull request by roypat**
Deprecating --startup-time-cpu-us accidentally involved us to double count some time spent in the jailer. This commit reverts that behavior.

A/B-Test to compare to commit before --startup-time-cpu-us deprecation:

```bash
 ./tools/devtool test --ab -- run b546bc566244695d0c709a318c30d483fb86ed2c HEAD --test integration_tests/performance/test_process_startup_time.py

...

Doing A/B-test for dimensions frozenset({('rootfs', 'ubuntu-22.04.squashfs'), ('performance_test', 'test_startup_time_new_pid_ns'), ('host_kernel', 'linux-6.5'), ('cpu_model', '11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz'), ('guest_kernel', 'linux-5.10'), ('vcpus', '2'), ('instance', 'NA'), ('guest_memory', '1024.0MB')}) and property startup_time
Doing A/B-test for dimensions frozenset({('rootfs', 'ubuntu-22.04.squashfs'), ('performance_test', 'test_startup_time_daemonize'), ('host_kernel', 'linux-6.5'), ('cpu_model', '11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz'), ('guest_kernel', 'linux-5.10'), ('vcpus', '2'), ('instance', 'NA'), ('guest_memory', '1024.0MB')}) and property startup_time
Doing A/B-test for dimensions frozenset({('rootfs', 'ubuntu-22.04.squashfs'), ('performance_test', 'test_startup_time_custom_seccomp'), ('host_kernel', 'linux-6.5'), ('cpu_model', '11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz'), ('guest_kernel', 'linux-5.10'), ('vcpus', '2'), ('instance', 'NA'), ('guest_memory', '1024.0MB')}) and property startup_time
No regressions detected!
[Firecracker devtool 2024-02-27T11:03:47+00:00] Finished test run ...


```

Fixes: 21f0dea22aa1bb38daf32520b1196a9ff72b5815

## Changes

...

## Reason

...

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this
  PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet
  [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

______________________________________________________________________

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by zulinx86 — APPROVED** [review]

**Comment by zulinx86** [comment]
Do we need to apply the same thing to https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L700-L701 ? and remove these lines https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L675-L676 ?

**Comment by roypat** [comment]
> Do we need to do something to
> 
> https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L700-L701
> and
> 
> https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L675-L676
> ?

The `CLOCK_PROCESS_CPUTIME_ID` is reset to 0 on `fork()` [[1]], so we only need to adjust once (the adjustment being done after the last fork is a bit... misleading here, as if we daemonize, the "extra" time that we want to subtract is added by the assignment in https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L675-L676. However, if we don't daemonize, then it is only added in https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L728 (whereas with daemonize, this last addition only adds the time since the final fork), so the "easiest" way to do the subtraction is in line 728).

[1]: https://stackoverflow.com/a/23642605

**Comment by zulinx86** [comment]
Does this work on both daemonized and non-daemonized jailers?
`jailer_start_time_cpu` is taken before fork() but the subtraction happens after fork().

**Review by pb8o — APPROVED** [review]
Thanks!

**Comment by zulinx86** [comment]
> > Do we need to do something to
> > https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L700-L701
> > 
> > and
> > https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L675-L676
> > 
> > ?
> 
> The `CLOCK_PROCESS_CPUTIME_ID` is reset to 0 on `fork()` [[1](https://stackoverflow.com/a/23642605)], so we only need to adjust once (the adjustment being done after the last fork is a bit... misleading here, as if we daemonize, the "extra" time that we want to subtract is added by the assignment in
> 
> https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L675-L676
> 
> . However, if we don't daemonize, then it is only added in
> https://github.com/firecracker-microvm/firecracker/blob/2dbb076919a3173036f8485d57031c3108c546f5/src/jailer/src/env.rs#L728
> 
> (whereas with daemonize, this last addition only adds the time since the final fork), so the "easiest" way to do the subtraction is in line 728).

Thanks for the explanation. I finally understood how it works... lol

just for myself, let me post my understanding.

if not daemonized
```
                           run()
|<-(jailer_start_time_cpu)->|<------------(jailer_cpu_time_us)----------->|
|<-------------------------------(L728)---------------------------------->|
```

if daemonized
```
                           run()
|<-(jailer_start_time_cpu)->|
|<----------(first fork)------------>|
                                     |<-----(second fork)------>|
                                                                |<-(L728)->|
```

**Pull request merged**
