### PR TITLE
[deps]: Updated dependency

### PR DESCRIPTION
**Pull request by AlexandruCihodaru**
Updated upstream vm-memory to be the same with the one from
io-uring crate

Signed-off-by: AlexandruCihodaru <cihodar@amazon.com>

# Reason for This PR

`[Author TODO: add issue #.]`
`[Open the PR after the related issue has a clear conclusion.]`
`[If there is no issue which states the need for this PR, create one first.]`
Fixes #

## Description of Changes

`[Author TODO: add description of changes.]`

- [ ] This functionality can be added in [`rust-vmm`][1].

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The issue which led to this PR has a clear conclusion.
- [x] This PR follows the solution outlined in the related issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes follow the [Runbook for Firecracker API changes][2].
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

[1]: https://github.com/rust-vmm
[2]: ../docs/api-change-runbook.md

### CODE REVIEW

**Comment by alindima** [comment]
We need v0.7.0 for io_uring since it's the first version including this: https://github.com/rust-vmm/vm-memory/commit/a49a173346aeb02061f2a6e9d6245c2c10273798

**Review by serban300 — APPROVED** [review]

**Review by alindima — CHANGES_REQUESTED** [review]
We need v0.7.0 for io_uring since it's the first version including this: rust-vmm/vm-memory@a49a173

**Comment by alindima** [comment]
Opened a new PR for this: https://github.com/firecracker-microvm/firecracker/pull/2844

**Review by alindima — DISMISSED** [review]

**Review by serban300 — APPROVED** [review]

**Comment by dianpopa** [comment]
As per my previous comment in Alin's PR, we should strive to use our local vm-memory wrapper all over Firecracker even if the additional defines (i.e AtomicBitmap enabled MmapRegions) are not necessary. The wrapper should re-export upstream vm-memory and act as an intermediate between Fc and upstream vm-memory. In this way, we will not be forced to update the upstream vm-memory in 2 places. Here are the changes needed in order to do that: https://github.com/dianpopa/firecracker/commit/7717710b8e9a72d6bdf120f93c02f79a46c980a5.

**Review by alindima — APPROVED** [review]

**Review by serban300 — APPROVED** [review]

**Pull request merged**
