### PR TITLE
Fix spelling of 'nomodule' kernel param

### PR DESCRIPTION
**Pull request by bduffany**
## Changes

Changes "nomodules" in the default kernel cmdline to "nomodule", the correct spelling. The old argument was not recognized by the kernel and incorrectly forwarded to init binaries.

Reference: https://www.kernel.org/doc/html/v4.10/admin-guide/kernel-parameters.html

Note, **this is a breaking change** for anyone who is relying on the default kernel command line, and happens to be loading kernel modules at runtime - or if their init binary was inadvertently relying on `nomodules` to be present in argv.

Fixes https://github.com/firecracker-microvm/firecracker/issues/4090

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by xmarcalx** [comment]
Thanks a lot for contributing also the fix!

I enabled the tests to run and I think we will need to add a changelog entry for this fix, highlighting the possibility of be a breaking change like you correctly suggested in the body of the description of the issue.

For the rest looks good, pending result of the tests.

**Comment by xmarcalx** [comment]
The issue on the firecracker-pr pipeline related to sec_audit is related to #4085, so does not require any action from you, we just need to rebase this branch on top of that.
Style of the commit (add a body description) need to be fixed which together with the previous message seems to be the only changes required.

**Comment by bduffany** [comment]
> I think we will need to add a changelog entry for this fix, highlighting the possibility of be a breaking change

Done

> Style of the commit (add a body description) need to be fixed

Done

**Review by bchalios — APPROVED** [review]
LGTM

**Review by xmarcalx — APPROVED** [review]
LGTM thanks a lot for the contribution!

**Review by bchalios — COMMENTED** [review]
On a second thought, this is not a breaking change, this is a bug in Firecracker exactly because of this:

> This may also break setups which use the
  default kernel command line and which use an init binary that
  inadvertently depends on the misspelled param ("nomodules") being
  present at the command line, since this param will no longer be passed.

Shall we update this entry to reflect that? WDYT @xmarcalx ?

**Review by bchalios — CHANGES_REQUESTED** [review]
Discarding my previous approval until we decide what to do with that.

**Review by bchalios — APPROVED** [review]
Ok, I understand why this is a breaking change. Just for documenting it:

With this change we break users who were using the default command line **and** loading modules. In reality this should not work, but due to the bug (`nomodule` vs `nomodules`) it would. So fixing the bug, it would break these users.

I believe that this CHANGELOG entry describes well the situation and it should be enough.

**Pull request merged**
