### PR TITLE
Allow whitelist of syscalls to be passed by user

### PR DESCRIPTION
**Pull request by mi-yu**
## Reason for This PR

Allow users to run Firecracker with a configurable custom whitelist of syscalls to avoid the need to recompile a new binary. See #1366 for more details.

## Description of Changes

- Added a new optional configuration field (to be documented), `syscall-whitelist`. An example of configuration is below:

```
{
    // other config options

    "syscall-whitelist": [
        {
            "arch": "x86_64",
            "toolchain": "musl",
            "syscalls": [
                39
            ]
        },
        {
            "arch": "aarch64",
            "toolchain": "musl",
            "syscalls": [
                8,
                12,
                15
            ]
        }
    ]
}
```

- Whitelists are configured per architecture and per toolchain and represented by a list of syscall numbers. Currently, there is no syscall number validation it is up to the user to provide valid syscall numbers. Additionally, whitelisted syscalls are all added to the seccomp filter with the `Allow` action, conditionals/argument-based filters not implemented.

- Whitelisted syscalls are merged with default syscalls (as specified by the `seccomp-level` option)

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`  
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [x] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided. 
- [x] The description of changes is clear and encompassing.
- [ ] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [ ] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [x] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [ ] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.
- [x] Either no new `unsafe` code has been added, or, the newly added `unsafe`
      code is unavoidable and properly documented.

### CODE REVIEW

**Comment by mi-yu** [comment]
I'm working on cleaning up commit messages and docs, but in the meantime are there any suggestions/concerns about the structure of the changes?

**Comment by mi-yu** [comment]
Hi @acatangiu, thanks for the followup! No worries about the timeline. In response to your points:

- My initial implementation first applied the default syscalls, then tried to apply the custom whitelist, but it seemed to crash the process. If I understand correctly, this is because the syscall to update the filters is not whitelisted. Is this actually the case? If so, would the API endpoint be readonly and just return the list of whitelisted syscalls?
- I have an implementation of per-thread filtering (addressing #1178), but haven't pushed it to my fork yet. It builds off of the changes in this PR, and I wanted to get the changes in this PR reviewed first.
- Ideally we allow users to pass in syscalls by name rather than by number for better UX, but I didn't find an easy way to map from syscall name to number. I was looking for something that lets me check whether or not a variable is exported from the `libc` crate, is that possible in Rust?

**Comment by aghecenco** [comment]
Hi @mi-yu, I'm going to jump in and work with you on the design and UX here :beer: 

In the meantime, quick answers:

> this is because the syscall to update the filters is not whitelisted. Is this actually the case? 

That's right, `prctl` is not whitelisted (nor should it be). We have to think a lot about what to apply and in which order. We'll iterate on this in the design phase.

> Ideally we allow users to pass in syscalls by name rather than by number for better UX

Agreed.

> I didn't find an easy way to map from syscall name to number. I was looking for something that lets me check whether or not a variable is exported from the libc crate, is that possible in Rust?

Not that I know of; what's more, `libc` doesn't export all of them, so we shouldn't count on it. Off the top of my head it looks like we should hardcode the mappings somewhere.

**Comment by mi-yu** [comment]
@aghecenco thanks for the clarifications! Just curious, is there a reason why `libc` doesn't export all syscalls?

Since it doesn't seem like there isn't a simple alternative, I can add a hardcoded list of syscalls to the code.

**Comment by aghecenco** [comment]
@mi-yu I don't know, maybe some just got omitted. @dianpopa found one a while back, see https://github.com/rust-lang/libc/issues/1348. On second thought, maybe it would be better - and it would definitely be cleaner - to do what she did and add any new missing ones to `libc`, then consume them from there instead. That way you'd enrich one codebase while not unnecessarily complicating Firecracker.

**Comment by petreeftime** [comment]
This PR changes the interface for installing seccomp filters slightly so it might impact your PR: https://github.com/firecracker-microvm/firecracker/pull/1474.

**Comment by mi-yu** [comment]
@petreeftime thanks for the heads up!

@aghecenco adding the missing syscalls to the `libc` crate would definitely be cleaner, but would that solve the issue? We still need a way to check if a user supplied string is exported as a variable from `libc` and read the value, right?

**Comment by aghecenco** [comment]
> @aghecenco adding the missing syscalls to the `libc` crate would definitely be cleaner, but would that solve the issue? We still need a way to check if a user supplied string is exported as a variable from `libc` and read the value, right?

Yeah, but at least it can be autogenerated if libc exports everything we need :+1:

**Comment by aghecenco** [comment]
Hi @mi-yu, @pyrito, I added some thoughts on https://github.com/firecracker-microvm/firecracker/issues/1366#issuecomment-572637218, WDYT?

**Comment by mi-yu** [comment]
Closing in favor of making new PR with cleaner git history

**Pull request closed without merging**
