### PR TITLE
Complete switch to Rust 2018 edition

### PR DESCRIPTION
**Pull request by damienstanton**
Issue #, if available: #839

Description of changes: Refactors to each crate to conform with 2018 edition idioms, and general cleanup of import paths, lifetime annotations, dyn for traits, etc.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dianpopa** [comment]
@damienstanton are you still interested in merging this PR?
If yes, please take into account when solving conflicts that we upgraded to rust 1.35.0, See #1139.

**Comment by damienstanton** [comment]
Will do, thanks!

**Comment by dianpopa** [comment]
Closing this due to inactivity.
@damienstanton feel free to reopen it when desiring to resume work.

**Comment by damienstanton** [comment]
Thanks @dianpopa, I've been away on family leave. I'm back now and have restarted work on this from a fresh branch off master (incl 1.3.5), so I will reopen a new PR for #839 from that branch rather than backtracing and merging this one.

**Comment by dianpopa** [comment]
Ok, we are looking forward to the new PR.

**Pull request closed without merging**
