### PR TITLE
[Balloon] Remove `must_tell_host` device feature

### PR DESCRIPTION
**Pull request by georgepisaltu**
## Reason for This PR

The `must_tell_host` feature is not useful to any use case as of now because of the fact that the device does not offer page poisoning functionality. Therefore, since it is not useful, it should be removed.

## Description of Changes

Removed the `must_tell_host` feature of the balloon device.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- ~~[ ] Any newly added `unsafe` code is properly documented.~~
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- ~~[ ] Any user-facing changes are mentioned in `CHANGELOG.md`.~~
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Review by sandreim — COMMENTED** [review]
Looks good, please also remove it from the docs.

**Review by georgepisaltu — COMMENTED** [review]
Forgot to add the documentation commit, PTAL.

**Review by alindima — APPROVED** [review]

**Review by alindima — COMMENTED** [review]
I think we should also add a Changelog.md entry

**Comment by georgepisaltu** [comment]
> I think we should also add a Changelog.md entry

I thought about it, but we haven't released the balloon version yet and it feels clunky to have "Added virtio balloon" and "Removed feature from balloon" in the same version entry in `Changelog.md`.

@sandreim can you take another look?

**Review by acatangiu — APPROVED** [review]

**Pull request merged**
