### PR TITLE
refactor: error_impl_error in Cargo.toml

### PR DESCRIPTION
**Pull request by jaoleal**
Add: error_impl_error in Cargo.toml so clippy does warn when a error is implemented as error

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the
    best of my knowledge, is covered under an appropriate open
    source license and I have the right under that license to
    submit that work with modifications, whether created in whole
    or in part by me, under the same open source license (unless
    I am permitted to submit under a different license), as
    Indicated in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including
    all personal information I submit with it, including my
    sign-off) is maintained indefinitely and may be redistributed
    consistent with this project or the open source license(s)
    involved.

## Changes

...

## Reason

...

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this
  PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet
  [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

______________________________________________________________________

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by JonathanWoollett-Light — COMMENTED** [review]
I would suggest the commit title:

> refactor: Warn on `clippy::error_impl_error`

**Comment by JonathanWoollett-Light** [comment]
The changes in this PR should also fix the warnings from enabling the lint.

E.g. https://buildkite.com/firecracker/firecracker-pr/builds/9322#018e2e69-a45b-4fcc-a15b-ae495f92de25/56-409

**Comment by jaoleal** [comment]
>the commit message should contain a description of the changes.

"Add: error_impl_error in Cargo.toml so clippy does warn when a error is implemented as error"

this isnt enough ?

**Comment by JonathanWoollett-Light** [comment]
@jaoleal I've updated this PR with the fixes, does it look okay to merge?

**Comment by jaoleal** [comment]
> @jaoleal I've updated this PR with the fixes, does it look okay to you?

Yeah, nice good first issue btw... i got the point now, renaming the error enum help to understand the code.

**Review by zulinx86 — APPROVED** [review]

**Review by JonathanWoollett-Light — APPROVED** [review]

**Comment by JonathanWoollett-Light** [comment]
Closes #4494 4488

**Pull request merged**
