### PR TITLE
[snapshot] fix bench build

### PR DESCRIPTION
**Pull request by serban300**
## Reason for This PR

[snapshot] fix bench build

## Description of Changes

fix `cargo build --all --all-targets ` issues the following error because of the missing criterion dependency.

```
error[E0432]: unresolved import `criterion`
 --> src/snapshot/benches/main.rs:3:5
  |
3 | use criterion::{black_box, criterion_group, criterion_main, Criterion};
  |     ^^^^^^^^^ use of undeclared type or module `criterion`

error[E0432]: unresolved import `criterion`
 --> src/snapshot/benches/version_map.rs:3:5
  |
3 | use criterion::{black_box, criterion_group, Criterion};
  |     ^^^^^^^^^ use of undeclared type or module `criterion`

error: cannot determine resolution for the macro `criterion_group`
   --> src/snapshot/benches/version_map.rs:140:1
    |
140 | criterion_group! {
    | ^^^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `criterion_group`
   --> src/snapshot/benches/main.rs:189:1
    |
189 | criterion_group! {
    | ^^^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `criterion_main`
   --> src/snapshot/benches/main.rs:195:1
    |
195 | criterion_main! {
    | ^^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error[E0601]: `main` function not found in crate `main`
   --> src/snapshot/benches/main.rs:3:1
    |
3   | / use criterion::{black_box, criterion_group, criterion_main, Criterion};
4   | | use snapshot::Snapshot;
5   | | use versionize::{VersionMap, Versionize, VersionizeError, VersionizeResult};
6   | | use versionize_derive::Versionize;
...   |
197 | |     version_map::benches,
198 | | }
    | |_^ consider adding a `main` function to `src/snapshot/benches/main.rs`

error: aborting due to 6 previous errors

```

`[Author TODO: add description of changes.]`

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Review by iulianbarbu — COMMENTED** [review]
:astonished: Lots of deps. Are these dependencies going to be compiled every time we run tests or compile firecracker in debug mode?

**Comment by georgepisaltu** [comment]
> 😲 Lots of deps. Are these dependencies going to be compiled every time we run tests or compile firecracker in debug mode?

I think dev dependencies are compiled when we run `cargo test`, not when we compile either debug or release binaries.

**Comment by iulianbarbu** [comment]
It seems criterion is compiled only when we use `cargo build` with `--all-targets`.

**Comment by serban300** [comment]
> astonished Lots of deps. Are these dependencies going to be compiled every time we run tests or compile firecracker in debug mode?

True, I know. They won't be compiled when we run `cargo test` or `cargo build` on the firecracker project. They are compiled when we run  `cargo build --all --all-targets` on the firecracker project. They are also compiled when running `cargo test` or `cargo bench` on the snapshot crate.

**Review by georgepisaltu — APPROVED** [review]

**Comment by iulianbarbu** [comment]
Can we enforce that criterion and its deps to be compiled only for `bench` target? 

It seems they are always compiled when running `cargo test --all` (which does not run bench tests, as far as I can tell). The bench tests can run in exclusive manner if run with `cargo test --benches` or with `cargo bench`.

**Comment by serban300** [comment]
> Can we enforce that criterion and its deps to be compiled only for `bench` target?
> 
> It seems they are always compiled when running `cargo test --all` (which does not run bench tests, as far as I can tell). The bench tests can run in exclusive manner if run with `cargo test --benches` or with `cargo bench --all`.

It might be doable using features, but I don't know if it's recommended. In the official criterion documentation it is specified as a dev-dependency: https://bheisler.github.io/criterion.rs/book/getting_started.html

**Comment by iulianbarbu** [comment]
Can we separate bench

> > Can we enforce that criterion and its deps to be compiled only for `bench` target?
> > It seems they are always compiled when running `cargo test --all` (which does not run bench tests, as far as I can tell). The bench tests can run in exclusive manner if run with `cargo test --benches` or with `cargo bench --all`.
> 
> It might be doable using features, but I don't know if it's recommended. In the official criterion documentation it is specified as a dev-dependency: https://bheisler.github.io/criterion.rs/book/getting_started.html

I see. The `test_unittests.py` and `test_coverage.py` tests will have a slightly bigger duration because they will need to compile criterion and its deps without actually needing them. I do not know how long they (will) take on our CI x86_64 machine, but I expect it to be unnoticeable. Do you think it is concerning? Should we invest effort in avoiding this increase by having these deps only for bench target?

**Comment by serban300** [comment]
> > > Can we enforce that criterion and its deps to be compiled only for `bench` target?
> > > It seems they are always compiled when running `cargo test --all` (which does not run bench tests, as far as I can tell). The bench tests can run in exclusive manner if run with `cargo test --benches` or with `cargo bench --all`.
> > 
> > 
> > It might be doable using features, but I don't know if it's recommended. In the official criterion documentation it is specified as a dev-dependency: https://bheisler.github.io/criterion.rs/book/getting_started.html
> 
> I see. The `test_unittests.py` and `test_coverage.py` tests will have a slightly bigger duration because they will need to compile criterion and its deps without actually needing them. I do not know how long they (will) take on our CI x86_64 machine, but I expect it to be unnoticeable. Do you think it is concerning? Should we invest effort in avoiding this increase by having these deps only for bench target?

An increase in the CI running time is undesirable, but the only alternative would be to use features which would be hacky. So personally I would keep it as a dev-dependency.

**Review by iulianbarbu — APPROVED** [review]

**Pull request merged**
