### PR TITLE
chore(logger): use thiserror::Error and simplify implementation

### PR DESCRIPTION
**Pull request by cm-iwata**
## Changes

This change will fix partof #3278.
I changed logger packages implementation to use thiserror::Error

I would like to continue working on #3278 and fix other packages

## Reason

ref #3278

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [ ] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] New `unsafe` code is documented.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

---

- [ ] This functionality can be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md

### CODE REVIEW

**Review by dianpopa — COMMENTED** [review]
Looks good but you need to change the commit title to something shorter:
I think 
```
logger: use thiserror::Error
```
suffices.

**Comment by cm-iwata** [comment]
@dianpopa 
Thank you for review.
Changed commit message.

**Review by dianpopa — DISMISSED** [review]

**Review by luminitavoicu — DISMISSED** [review]

**Comment by cm-iwata** [comment]
CI failed with this error. 
https://buildkite.com/firecracker/firecracker-aarch64-kernel-4-dot-14-ci/builds/2419#0184c894-3d60-4549-85f0-898251bd631d


Should I update the COVERAGE_DICT value like this commit?
https://github.com/firecracker-microvm/firecracker/commit/7e1c017f01b9dd05fe0d9aae5fab6b6d0d6ff325

**Comment by dianpopa** [comment]
> CI failed with this error. https://buildkite.com/firecracker/firecracker-aarch64-kernel-4-dot-14-ci/builds/2419#0184c894-3d60-4549-85f0-898251bd631d
> 
> Should I update the COVERAGE_DICT value like this commit? [7e1c017](https://github.com/firecracker-microvm/firecracker/commit/7e1c017f01b9dd05fe0d9aae5fab6b6d0d6ff325)

Yes, you need to update them with the new values form the last CI run.

**Comment by cm-iwata** [comment]
>Yes, you need to update them with the new values form the last CI run.

Thank you!!
Updated!

**Pull request merged**
