### PR TITLE
Minimize visibility for functions in dumbo

### PR DESCRIPTION
**Pull request by andrisak**
Signed-off-by: andrisak <andrisak@gmail.com>

# Reason for This PR

Minimize the visibiltity in `dumbo`, see #607.

## Description of Changes

Changed visibility for some functions in `dumbo`. A number of functions could be made private and are not currently used. This causes compilation warnings.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The reason for this PR is clearly provided (issue no. or explanation).
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any newly added `unsafe` code is properly documented.
- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

### CODE REVIEW

**Comment by dianpopa** [comment]
Hi @andrisak ,

The tests are failing due to the presence of multiple warnings. If you solve those, the tests should pass.

**Comment by andrisak** [comment]
Hi @dianpopa ,

Do you think the code should be deleted or should the warning just be silenced? For example, it seems like `dumbo/src/pdu/udp.rs` can be deleted but not sure if that's a good idea.

**Comment by dianpopa** [comment]
There are still tests there are failing. As far as my understanding, there are some unit tests that were using the deleted methods. You can also delete those too as far as my concern.

If you wish to test your changes before pushing them to upstream, you can use
```
./tools/devtool -y test -- ../tests/integration_tests/build/
```

**Review by acatangiu — COMMENTED** [review]
Let's take a good look at which fns make sense to be part of the public interface of the module and same for crate even if they're currently not used outside the module/crate.

Right now, the PR makes almost everything private, even object methods or module functions that are meant as public interface.

**Comment by acatangiu** [comment]
Unused code removal should ideally be separated to dedicated commits that have meaningful title and detailed description for what is being removed. It then makes it easy to find the code looking at git history if we end up ever needing it (we want to avoid having to write it again just because we don't know or forget we had it at some point).

**Comment by dianpopa** [comment]
@andrisak indeed the majority of the functions that you made private in this PR were intended as functions pertaining to dumbo's public interface. Even though they are not used by Firecracker we might in the future make this a standalone crate. Sorry for misleading you!

I am now closing this PR. If you feel there are still components for which we might want to minimize the visibility, make the adjustments and re-open the PR.

**Pull request closed without merging**
