### PR TITLE
Add link to nc-vsock tool in the documentation 

### PR DESCRIPTION
**Pull request by simonis**
nc-vsock doesn't seem to be a standard tool so I suggest providing a link to the repository.

### CODE REVIEW

**Comment by pb8o** [comment]
Thanks for the contribution! I recently learned that `socat` also supports VSOCK, it may be good to use a single tool for all the examples. https://stefano-garzarella.github.io/posts/2021-01-22-socat-vsock/

**Review by pb8o — APPROVED** [review]

**Comment by simonis** [comment]
> Thanks for the contribution! I recently learned that `socat` also supports VSOCK, it may be good to use a single tool for all the examples. https://stefano-garzarella.github.io/posts/2021-01-22-socat-vsock/

Thanks for your review. I totally agree that using `socat` alone is preferable. I've therefore updated the doc accordingly. Hope that's fine for you.

**Comment by pb8o** [comment]
Thanks! There is a couple of style checks that are failing https://buildkite.com/firecracker/firecracker-pr/builds/276#01855802-d595-421a-97ea-fdc197b174e8

Just a couple about line length limits, and one  about commits needing a signed-off line. You can fix that with `git commit --amend -s`.

**Comment by simonis** [comment]
I couldn't use `commit --amend` to sign older commits in this PR. Also, according to the style checks, the first commit in the PR had a too long summary. So I've decided to merge with latest upstream, squash, rebase and sign off locally and do a `--force` push. Hope this finally pacifies the automatic checks :)

**Comment by simonis** [comment]
Ping...

This is a trivial documentation fix. @pb8o, what's missing before it can be pushed?

The only tests that fails is a resume performance test which can hardly be caused by a documentation change in a Markdown file :)

**Review by dianpopa — APPROVED** [review]

**Review by pb8o — APPROVED** [review]

**Comment by simonis** [comment]
Thanks @pb8o & @dianpopa

**Pull request merged**
