### PR TITLE
Use micro-http from firecracker-microvm/micro-http

### LINKED ISSUE #1670: use micro-http from firecracker-microvm/micro-http
We have a few PRs touching the micro-http code that were merged to Firecracker. We should first port those PRs and then use it as a crate from firecracker-microvm/micro-http.

To avoid breaking the build, we should either use a specific commit from the micro-http repository, or create a tag and use that. After we publish it to crates.io we will not have that problem any more.

### PR DESCRIPTION
**Pull request by lyuyuan**
Signed-off-by: YUAN LYU <lyuyuan92@gmail.com>

# Reason for This PR

Fix #1670 

## Description of Changes

Use micro-http from firecracker-microvm/micro-http latest commit, `49240ce`.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [ ] The reason for this PR is clearly provided (issue no. or explanation).
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

### CODE REVIEW

**Comment by lyuyuan** [comment]
@serban300 @acatangiu Hi, I wonder if I can change coverage expectation for this PR since it only remove code?

**Comment by acatangiu** [comment]
> Hi, I wonder if I can change coverage expectation for this PR since it only remove code?

Definitely! Clearly no new _uncovered_ code is added; feel free to update expected coverage.

**Comment by lyuyuan** [comment]
@acatangiu Updated expected coverage. Please let me know if I need to make any changes.

**Review by acatangiu — DISMISSED** [review]
I manually diffed the embedded micro-http code with the crate code pulled in by this PR and confirm we're not missing anything (actually we're getting a couple of small bugfixes which we missing from firecracker) 👍 

@lyuyuan pls update coverage for AMD as well so we can merge

**Comment by acatangiu** [comment]
Also please note that https://github.com/firecracker-microvm/micro-http has renamed `master` to `main` so this PR needs to reflect that too.

**Comment by lyuyuan** [comment]
@acatangiu Thanks for reviewing. I have updated AMD expected coverage. I noticed one performance test is failing but seem irrelevant to our change. Is there a way to retry? On another note, this PR picks commit `49240ce` which seems already on branch `main` of micro-http after the renaming.

**Comment by georgepisaltu** [comment]
Hi @lyuyuan ,

The PR looks good, please update the AMD coverage to `83.98`.

**Comment by lyuyuan** [comment]
Hi @georgepisaltu , AMD coverage updated, thanks!

**Comment by acatangiu** [comment]
I've re-triggered CI

**Review by acatangiu — APPROVED** [review]

**Review by georgepisaltu — APPROVED** [review]

**Pull request merged**
