### PR TITLE
Fix unit test coverage for the cpuid crate

### PR DESCRIPTION
**Pull request by ahmedaabouzied**
## Reason for This PR
Solve issue #1705 

## Description of Changes
Set the mod block to `mod tests` instead of `mod test` in the `cpuid` crate. This will make the test code in `cpuid` crate get excluded by kcov. If it's not excluded kcov counts the test code as code and then the test coverage result gets messed up.

- [x] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.

### CODE REVIEW

**Comment by lauralt** [comment]
Hi, @ahmedaabouzied. Thanks for the PR!
The code coverage integration test is now failing. Can you please update the target value in `test_coverage.py`?

**Comment by ahmedaabouzied** [comment]
@lauralt, Sure. I'll do that shortly.

**Comment by ahmedaabouzied** [comment]
I had to amend the commit then force push it to update the value of `COVERAGE_TARGET_PCT` to a suitable value to pass the `test_coverage` integration test without committing twice for the same thing. I don't know if this is the best git approach to do. I'd appreciate if someone proposes a better solution.

**Comment by ahmedaabouzied** [comment]
the `test_coverage` now passes locally, at least I can now hope it passes on the CI test
```bash
===================================================================================== test session starts ====================================================================================$
platform linux -- Python 3.6.9, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
cachedir: ../build/pytest_cache
rootdir: /firecracker/tests, inifile: pytest.ini
plugins: timeout-1.3.4
timeout: 300.0s
timeout method: signal
timeout func_only: False
collected 1 item

[ unsafe | 1 tests | 1 worker(s) ]


  PASSED    integration_tests/build/test_coverage.py::test_coverage

================================================================================ 1 passed in 135.26s (0:02:15) ===============================================================================$

```

**Comment by lauralt** [comment]
> I had to amend the commit then force push it to update the value of `COVERAGE_TARGET_PCT` to a suitable value to pass the `test_coverage` integration test without committing twice for the same thing. I don't know if this is the best git approach to do. I'd appreciate if someone proposes a better approach.

Hmm, it looks like now you have a separate commit just for the coverage change. This should be in the same commit with the other changes. Because it's a small change, you can just remove the last commit: `git reset --hard HEAD^`, now the coverage target will have the old value, you can change it to the new one: 84.08, and then run `git commit -a --amend` and this change should be added to your first commit.
Another option (a nicer one, but in this case takes more time) would be to squash your last two commits, as explained here: https://webkul.com/blog/how-to-squash-multiple-git-commits/.

**Comment by lauralt** [comment]
> > I had to amend the commit then force push it to update the value of `COVERAGE_TARGET_PCT` to a suitable value to pass the `test_coverage` integration test without committing twice for the same thing. I don't know if this is the best git approach to do. I'd appreciate if someone proposes a better approach.
> 
> Hmm, it looks like now you have a separate commit just for the coverage change. This should be in the same commit with the other changes. Because it's a small change, you can just remove the last commit: `git reset --hard HEAD^`, now the coverage target will have the old value, you can change it to the new one: 84.08, and then run `git commit -a --amend` and this change should be added to your first commit.
> Another option (a nicer one, but in this case takes more time) would be to squash your last two commits, as explained here: https://webkul.com/blog/how-to-squash-multiple-git-commits/.

Or, as @iulianbarbu pointed out, you can just `git reset HEAD^`, the coverage change will still be around, but not commited; to append it to your first commit, just run `git commit -a --amend` (I'm still learning git myself :D).

**Comment by ahmedaabouzied** [comment]
That makes sense. I just squashed the commits and force pushed the changes.

**Comment by lauralt** [comment]
> That makes sense. I just squashed the commits and force pushed the changes.

Great! Now it looks good.
Just a small observation: we don't usually mention in the commit message if the coverage target increased or decreased; this is somehow implied by the actual changes that are brought by the commit. I would leave the commit message as it was before.

**Comment by ahmedaabouzied** [comment]
Okay. So should I change the commit message?

**Comment by lauralt** [comment]
> Okay. So should I change the commit message?

Yep, it would be nice and to be super clear you can update it like this:

Fix unit test coverage for the cpuid crate

Set the unit tests mod as 'tests' instead of 'test' in
cpuid crate, transformer module.

**Comment by ahmedaabouzied** [comment]
Now the `test_rx_rate_limiting` fails
```bash
=================================== FAILURES ===================================
____________________ test_rx_rate_limiting[ubuntu_with_ssh] ____________________
integration_tests/functional/test_rate_limiter.py:152: in test_rx_rate_limiting
    _check_rx_rate_limit_patch(test_microvm, guest_ips)
integration_tests/functional/test_rate_limiter.py:377: in _check_rx_rate_limit_patch
    _check_rx_bandwidth(test_microvm, guest_ips[1], bandwidth_kb)
integration_tests/functional/test_rate_limiter.py:426: in _check_rx_bandwidth
    assert diff_pc < MAX_BYTES_DIFF_PERCENTAGE
E   assert 10.6796875 < 10
```
I'll check it out

**Comment by lauralt** [comment]
> Now the test `test_rx_rate_limiting` fails
> 
> ```shell
> =================================== FAILURES ===================================
> ____________________ test_rx_rate_limiting[ubuntu_with_ssh] ____________________
> integration_tests/functional/test_rate_limiter.py:152: in test_rx_rate_limiting
>     _check_rx_rate_limit_patch(test_microvm, guest_ips)
> integration_tests/functional/test_rate_limiter.py:377: in _check_rx_rate_limit_patch
>     _check_rx_bandwidth(test_microvm, guest_ips[1], bandwidth_kb)
> integration_tests/functional/test_rate_limiter.py:426: in _check_rx_bandwidth
>     assert diff_pc < MAX_BYTES_DIFF_PERCENTAGE
> E   assert 10.6796875 < 10
> ```
> 
> I'll check it out

This is a problem on our side that we're trying to fix: #1809. Just another `push -f` would be appreciated. Sorry for this :(.

**Comment by raduiliescu** [comment]
> 
> 
> Now the test `test_rx_rate_limiting` fails
> 
> ```shell
> =================================== FAILURES ===================================
> ____________________ test_rx_rate_limiting[ubuntu_with_ssh] ____________________
> integration_tests/functional/test_rate_limiter.py:152: in test_rx_rate_limiting
>     _check_rx_rate_limit_patch(test_microvm, guest_ips)
> integration_tests/functional/test_rate_limiter.py:377: in _check_rx_rate_limit_patch
>     _check_rx_bandwidth(test_microvm, guest_ips[1], bandwidth_kb)
> integration_tests/functional/test_rate_limiter.py:426: in _check_rx_bandwidth
>     assert diff_pc < MAX_BYTES_DIFF_PERCENTAGE
> E   assert 10.6796875 < 10
> ```
> 
> I'll check it out

Have you updated the branch before the push? A tentative fix was put in yesterday.

**Comment by lauralt** [comment]
> > Now the test `test_rx_rate_limiting` fails
> > ```shell
> > =================================== FAILURES ===================================
> > ____________________ test_rx_rate_limiting[ubuntu_with_ssh] ____________________
> > integration_tests/functional/test_rate_limiter.py:152: in test_rx_rate_limiting
> >     _check_rx_rate_limit_patch(test_microvm, guest_ips)
> > integration_tests/functional/test_rate_limiter.py:377: in _check_rx_rate_limit_patch
> >     _check_rx_bandwidth(test_microvm, guest_ips[1], bandwidth_kb)
> > integration_tests/functional/test_rate_limiter.py:426: in _check_rx_bandwidth
> >     assert diff_pc < MAX_BYTES_DIFF_PERCENTAGE
> > E   assert 10.6796875 < 10
> > ```
> > 
> > 
> > I'll check it out
> 
> Have you updated the branch before the push? A tentative fix was put in yesterday.

It failed after I updated his branch.

**Pull request merged**
