### PR TITLE
Add missing TIOCGWINSZ ioctl param.

### PR DESCRIPTION
**Pull request by alindima**
## Reason for This PR

During initial audit, I forgot to allow the `TIOCGWINSZ` param for the `ioctl` syscall.
This was not caught by the CI, because this param is used while shutting down the VM, and the bad syscall signal also resulted in exiting the process.
This was caught by running the test suite after removing the `exit()` call in the `sigsys_handler`.

**Because of a rebase from master, there are many commits in this PR. You only need to review the [latest commit](https://github.com/firecracker-microvm/firecracker/pull/2132/commits/9bd6f1f360d234d069d8e8d49189bbf2522b6014)**

## Description of Changes

Allow `TIOCGWINSZ` as a param for `ioctl`
Updated the `test_shut_down.py` test. Now it checks that the process was not killed due to a seccomp fault. This is what caused the bug.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by gc-plp** [comment]
Could we protect ourselves against missing signals like these?

**Comment by alindima** [comment]
> Could we protect ourselves against missing signals like these? (e.g. having an unit test)

I will update the test_shut_down.py to also check the seccomp num_faults metric. This should act as a regression test and will make sure that the process is not killed because of a seccomp violation

**Comment by alindima** [comment]
> > Could we protect ourselves against missing signals like these? (e.g. having an unit test)
> 
> I will update the test_shut_down.py to also check the seccomp num_faults metric. This should act as a regression test and will make sure that the process is not killed because of a seccomp violation

Done, @gc-plp please take a look

**Comment by raduiliescu** [comment]
Since you are developing on a feature branch, please separate the integration of changes from main into a separate PR. You have 18 commits in this PR and would be nice to have one only with your commits.

**Comment by alindima** [comment]
> Since you are developing on a feature branch, please separate the integration of changes from main into a separate PR. You have 18 commits in this PR and would be nice to have one only with your commits.

Thank you for the suggestion. I gathered feedback from the team when opening the PR and it seemed acceptable to have this kind of PR. I added in the description the exact commit that needs reviewing.

I agree that it would be nicer to split these kind of PRs. For the purposes of this particular one, I will leave it as-is, but in the future, I will create a separate PR for rebasing from mainline

**Review by gc-plp — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Pull request merged**
