### PR TITLE
Simplify read_config

### PR DESCRIPTION
**Pull request by kornelski**
## Changes

`read_config` doesn't have to use `io::Write` to just copy bytes in memory.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

### CODE REVIEW

**Review by ShadowCurse — COMMENTED** [review]
Overall everything looks good, but please update commit messages (otherwise CI will be angry). Also can you update the `write_config` as well while you are at it?

**Review by bchalios — CHANGES_REQUESTED** [review]
Sorry for the delay @kornelski  @ShadowCurse,

I don't think there's any danger from failed reads/writes. At least, not on the host side. If the guest kernel driver is not working properly it might fail, but that's the guest's problem. We do the right thing.

LGTM, apart from the commit messages. Would you mind adding a bit of more info on what each commit does and why? Also, really a nit, but we typically have commit titles like:

`virtio: simplify read_config for VirtIO devices`

**Comment by ShadowCurse** [comment]
@kornelski Also please fix compilations/stylistics errors from here: https://buildkite.com/firecracker/firecracker-pr/builds/9248#_

**Comment by bchalios** [comment]
Hi @kornelski, could you fix the style issues in the PR so we can merge this?

**Review by roypat — APPROVED** [review]

**Comment by roypat** [comment]
Hi @kornelski, 
I've gone ahead and fixed up the style issues so that we can go ahead with merging this improvement. Thanks again for your contribution!

**Review by ShadowCurse — APPROVED** [review]

**Review by bchalios — APPROVED** [review]

**Pull request merged**
