### PR TITLE
[v0.25][backport] cpuid: adapt templates for kernel 5.10

### PR DESCRIPTION
**Pull request by alindima**
# Reason for This PR

Backport of https://github.com/firecracker-microvm/firecracker/pull/2795

## Description of Changes

Explicitly mask the aforementioned features

- [ ] This functionality can be added in [`rust-vmm`][1].

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The issue which led to this PR has a clear conclusion.
- [x] This PR follows the solution outlined in the related issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes follow the [Runbook for Firecracker API changes][2].
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

[1]: https://github.com/rust-vmm
[2]: ../docs/api-change-runbook.md

### CODE REVIEW

**Review by serban300 — COMMENTED** [review]
Looks good ! Just one think. Shouldn't we merge the change in main first and then backport it to 0.25 ?

**Comment by alindima** [comment]
> Looks good ! Just one think. Shouldn't we merge the change in main first and then backport it to 0.25 ?

opened https://github.com/firecracker-microvm/firecracker/pull/2795

**Review by serban300 — APPROVED** [review]

**Comment by alindima** [comment]
Added a changelog entry

**Review by serban300 — APPROVED** [review]

**Review by AlexandruCihodaru — APPROVED** [review]
🚢

**Pull request merged**
