### PR TITLE
Use 0x40000010 CPUID leaf to announce frequencies

### PR DESCRIPTION
**Pull request by cperciva**
The 0x40000010 CPUID leaf is used to announce TSC and local APIC frequencies to VM guests; this allows them to boot faster by bypassing clock calibration loops.

## Changes

In x86_64 initialization, passes the TSC frequency to cpuid.normalize, which then (a) updates the 0x40000000 CPUID leaf to announce support for leaves up to 0x40000010, and (b) adds a 0x40000010 CPUID leaf to announce the TSC frequency and LAPIC frequency (which is always 10^6 in KVM).

## Reason

Improve boot performance.  This leaf is already used in most other hypervisors, including EC2.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [N/A] If a specific issue led to this PR, this PR closes the issue.
- [X] The description of changes is clear and encompassing.
- [N/A] Any required documentation changes (code and docs) are included in this PR.
- [N/A] API changes follow the [Runbook for Firecracker API changes][2].
- [N/A] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [x] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by cperciva** [comment]
I need help from someone familiar with the snapshot restore code here -- I'm not sure if the TSC value is restored from the snapshot before we call cpuid.normalize.  If not we'll need to set the clock frequency CPUID leaf later.

**Comment by kalyazin** [comment]
> I need help from someone familiar with the snapshot restore code here -- I'm not sure if the TSC value is restored from the snapshot before we call cpuid.normalize. If not we'll need to set the clock frequency CPUID leaf later.

Hi. We do not call normalize() on the restore path. `set_tsc_khz()` is called by `load_snapshot()` internally.

**Comment by cperciva** [comment]
> Hi. We do not call normalize() on the restore path. `set_tsc_khz()` is called by `load_snapshot()` internally.

Oh, do snapshots store all of the CPUID state?  In that case there's nothing to worry about since the CPUID and TSC frequency should match.

**Comment by kalyazin** [comment]
> > Hi. We do not call normalize() on the restore path. `set_tsc_khz()` is called by `load_snapshot()` internally.
> 
> Oh, do snapshots store all of the CPUID state? In that case there's nothing to worry about since the CPUID and TSC frequency should match.

Yes, we are saving the CPUID state in the snapshot: https://github.com/firecracker-microvm/firecracker/blob/24adb76b907eb6b2690d5a4da1ced7cdd84d72f5/src/vmm/src/vstate/vcpu/x86_64.rs#L425 .

**Comment by cperciva** [comment]
> Yes, we are saving the CPUID state in the snapshot:

Perfect, thanks!

**Comment by cperciva** [comment]
Ok I think this is ready for review.

**Comment by kalyazin** [comment]
May I know what documentation you use to interpret semantics of `0x40000000` and `0x40000010` CPUID leaves? This would also be useful to include links in the commit message and the PR.

**Comment by cperciva** [comment]
> May I know what documentation you use to interpret semantics of `0x40000000` and `0x40000010` CPUID leaves? This would also be useful to include links in the commit message and the PR.

The original source of these is a proposal emailed to LKML by VMware in 2008: https://lwn.net/Articles/301888/

I'm not aware of any official documentation; everything I can find online points back at this proposal which seems to have been quietly accepted by rough consensus of working code.

**Comment by kalyazin** [comment]
> > May I know what documentation you use to interpret semantics of `0x40000000` and `0x40000010` CPUID leaves? This would also be useful to include links in the commit message and the PR.
> 
> The original source of these is a proposal emailed to LKML by VMware in 2008: https://lwn.net/Articles/301888/
> 
> I'm not aware of any official documentation; everything I can find online points back at this proposal which seems to have been quietly accepted by rough consensus of working code.

Thanks for the link. I had a brief look into the Linux kernel, but could not see how the guest would use these leaves. Is it something FreeBSD-specific? I think it would be useful to leave a trace in the PR/git as to which guests are likely to benefit from the change.

I also ran CI tests and they fail for 2 reasons on x86:
- we collect [CPU fingerprints](https://github.com/firecracker-microvm/firecracker/tree/main/resources/tests/cpu_template_helper) that include the CPUID value. They need to be updated to reflect the presence of the new leaves.
- we have a [CPU template helper tool](https://github.com/firecracker-microvm/firecracker/blob/main/docs/cpu_templates/cpu-template-helper.md) that can [dump](https://github.com/firecracker-microvm/firecracker/blob/main/docs/cpu_templates/cpu-template-helper.md#dump-command) guest CPU configuration. We have a [test](https://github.com/firecracker-microvm/firecracker/blob/main/tests/integration_tests/functional/test_cpu_template_helper.py#L240) that compares the dumped configuration with the configuration we read from the guest directly. This test fails with your change. It is not immediately clear to me why, but I suspect that the new leaves are not reported by `KVM_GET_SUPPORTED_CPUID`. We have an exception [list](https://github.com/firecracker-microvm/firecracker/blob/main/tests/integration_tests/functional/test_cpu_template_helper.py#L132C1-L132C31) for such leaves that may need to be updated. If this is the solution you choose, please leave a comment on why the leaves are excluded.

**Comment by cperciva** [comment]
> Thanks for the link. I had a brief look into the Linux kernel, but could not see how the guest would use these leaves. Is it something FreeBSD-specific? I think it would be useful to leave a trace in the PR/git as to which guests are likely to benefit from the change.

Huh.  It looks Linux only uses this when running under the ACRN hypervisor.  Which... is something the Lambda team will probably want to fix, because why not save a few ms on cold starts?

FWIW, Nitro provides this CPUID leaf, so there's clearly *someone* in Amazon who thought it was useful.  (Possibly Alex Graf?)

> I also ran CI tests and they fail for 2 reasons on x86:
> 
> * we collect [CPU fingerprints](https://github.com/firecracker-microvm/firecracker/tree/main/resources/tests/cpu_template_helper) that include the CPUID value. They need to be updated to reflect the presence of the new leaves.
> * we have a [CPU template helper tool](https://github.com/firecracker-microvm/firecracker/blob/main/docs/cpu_templates/cpu-template-helper.md) that can [dump](https://github.com/firecracker-microvm/firecracker/blob/main/docs/cpu_templates/cpu-template-helper.md#dump-command) guest CPU configuration. We have a [test](https://github.com/firecracker-microvm/firecracker/blob/main/tests/integration_tests/functional/test_cpu_template_helper.py#L240) that compares the dumped configuration with the configuration we read from the guest directly. This test fails with your change. It is not immediately clear to me why, but I suspect that the new leaves are not reported by `KVM_GET_SUPPORTED_CPUID`. We have an exception [list](https://github.com/firecracker-microvm/firecracker/blob/main/tests/integration_tests/functional/test_cpu_template_helper.py#L132C1-L132C31) for such leaves that may need to be updated. If this is the solution you choose, please leave a comment on why the leaves are excluded.

Thanks, I'll take a look at these.  I'm not sure why these didn't show up when I ran the tests... unless it's because I was running the tests in EC2 and it exposed values on the host matching what I was setting in Firecracker.

**Comment by kalyazin** [comment]
> FWIW, Nitro provides this CPUID leaf, so there's clearly _someone_ in Amazon who thought it was useful. (Possibly Alex Graf?)

Yes, Nitro does provide the leaf indeed.

> Huh. It looks Linux only uses this when running under the ACRN hypervisor. Which... is something the Lambda team will probably want to fix, because why not save a few ms on cold starts?

That may be out of our direct control. We would be happy to accept the change anyway.

**Comment by kalyazin** [comment]
@cperciva would you still like to continue to work on the PR? We would prefer to close it otherwise.

**Comment by cperciva** [comment]
@kalyazin Sorry about the long radio silence, I've been busy with other stuff in FreeBSD (among other things I got "promoted" to release engineering lead).  I do hope to return to this later but I can't promise any ETA so let's close the issue for now; I'll open a new one when I get back to Firecracker.

**Pull request closed without merging**
