### PR TITLE
release v0.16.0

### PR DESCRIPTION
**Pull request by acatangiu**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by acatangiu** [comment]
@andreeaflorescu updated version in Cargo.lock as well

**Comment by andreeaflorescu** [comment]
Don't we want to update the package versions as well? Aka running `cargo update`?

**Comment by acatangiu** [comment]
We're currently stuck with updating the crates as there are some upstream changes that break our seccomp validations. Until that's taken care of, we won't be doing `cargo update`. At least that's what I remember was decided on the `v0.15.0` release.

**Comment by acatangiu** [comment]
@andreeaflorescu @andreeaflorescu done

**Comment by andreeaflorescu** [comment]
We should first merge back to master the v0.15.1 branch so we can have the updated changelog.

**Pull request closed without merging**
