### PR TITLE
[io_uring] Test PR

### PR DESCRIPTION
**Pull request by serban300**
Test PR to investigate `test_5_inc_snapshots` failures

### CODE REVIEW

**Comment by sandreim** [comment]
Is this only happening with `io_uring` ? Asking because of this other similar issue: https://github.com/firecracker-microvm/firecracker/issues/2802

**Comment by serban300** [comment]
> @serban300 Is this only happening with `io_uring` ? Asking because of this other similar issue: #2802

Yes, this failure only occurs with `io_uring`.

**Comment by alindima** [comment]
I've seen this same failure without io_uring as well

**Comment by sandreim** [comment]
I would look at any dirty bitmap changes or vm-memory changes that might have been merged.

**Pull request closed without merging**
