### PR TITLE
OCI engine agnostic devtool (Issue #1973)

### PR DESCRIPTION
**Pull request by bbros-dev**
## Reason for This PR

Closes issue #1973 
Workaround issue #1980

## Description of Changes

OCI engine agnostic devtool

Closes issue #1973.
Workaround issue #1980.

These changes allow `tools/devtool build` and `tools/devtool test`
to Just-Work(TM) when a user has Podman and not Docker installed.

They provide a workaround for issue 1980 in so far as a user can
build and test under a typical user account - albeit with that
account has elevated privileges.
AFAIK this is not the same as building as the root with elevated
privileges.

Moving to rootless builds exposes several issues that are
odscured by building as root with `--cap-add=all`.
The first is arises from handing over the hosts whole device tree
to the container via `--volume dev:dev`.
Unprivleged, this generates a permissions error in the presense
of the `--tty` option.
Those issues have been resolved in this commit.

- Respects a DEBUG=1|y|yes|true flag that turns on xtrace for
  the script and adds RUST_LOG=rls=trace,cargo=trace for the
  Rust build.
- OPT_UNATTENDED is still respected, and users can also
  use devtool in pipes, such as `yes|tools/devtool test`
- Add `oci_engine_args_init` to accomodate the fact that Docker
  handles user namespacing at the daemon level and Podman
  uses an option.
- `ensure_docker` -> `ensure_oci_engine`. This now returns the OCI
  engine path. Where both Podman and Docker are installed,
  Podman is preferred. Simply because 1) the Podman default
  is to run rootless, 2) for users without either, Podman can be
  installed without elevated rights and need to configure a
  daemon for user name space functionality.
- `ensure_devctr` is refactored to consume the OCI engine
  returned by `ensure_oci_engine`.
- `ensure_build_dir` permissions change fallsback to use
   `cmd_fix_perms` in cases where root owns the folder.
- `cmd_fix_perms` allows us to do away with running a
  container to get elevated permissions to make the
  change - the dirty hack is gone.
- `cmd_fix_perms` now respects OPT_UNATTENDED,
  and `check_superuser` before invoking sudo for the
  recursive `chmod`. After sudo is used it is revoked
  in `uncheck_superuser` - here check has its "checkbox"
  meaning and not "inspect" meaning.
- `get_user_confirmation` now allows piped confirmation
  and respects OPT_UNATTENDED.
- `run_devctr` selects the OCI engine using the logic
  in `ensure_oci_engine`. Podman namespacing option
  is added in `oci_engine_args_init`. The `--tty` option is
  removed without loss of functionality, and this allows
  builds be done rootless.  Test runs still require root.
  The `--volume dev:dev` appears unneccessary to
  complete a build. The host exposing its device tree
  to the guest seems excessive.
- `cmd_build`: `cargo_args` fixes `--target ...` insertion - this broke
   my builds but I can't find any other reports. Nonetheless, it seems
  the right way to add space delimited items to a shell array. A
  `--ulimit 4096:4096` options is added. Withoput this my builds
  broke and this options was used elsewhere so it appears to have
  been an oversight here.
- `check_binary` is a new function. This is needed because it is so
  tricky to pass a bash function to sudo. Instead we set a flag and
  use that to invoke sudo on a file (the OCI engine).
- `check_superuser` sets the `run_with_sudo` flag, and gets the
  elevated root access if not already in hand.
- `uncheck_sudo` revokes the elevated sudo access.
- `run_as_root` does that.
- `main` now checks for specific known commands and so is limited
  in what it will run.

Together the 3 additional functions introduced allow us to remove
the workaround of changiung permissions by running an OCI engine
(Docker).
Changes, other than the above, are cosmetic.

Signed-off-by: Begley Brothers Inc <begleybrothers@gmail.com>

~~- [] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).~~

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
~~- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.~~
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.

### CODE REVIEW

**Comment by gc-plp** [comment]
> Where both Podman and Docker are installed,
> Podman is preferred. Simply because 1) the Podman default
> is to run rootless, 2) for users without either, Podman can be
> installed without elevated rights and need to configure a
> daemon for user name space functionality

Adding Podman as the default option will be confusing for people that have both runtimes installed, because it changes the way of working with `devtool`, for example when being asked for the root password.

The PR should conserve the current command parameters so that they're passed on as before and add Podman as an alternative to the default engine, which should be `docker`.

**Comment by bbros-dev** [comment]
@gc-plp, thanks for taking time to look over this. Appreciate the feedback.

> Podman as the default option will be confusing for people that have both runtimes installed

If they have Podman installed they likely already know it runs rootless by default.  
The fact that Docker *silently* runs a process as root with elevated privileges is *precisely* the reason it should be sent to the back of the queue ;)
That a Podman workflow prompts the user before going ahead with elevated access is the intent of the changes - a feature not a bug. Unless of course they did `sudo devtool build`, but most Podman users seem to know one point for having Podman is that things run in user space, and prompt you when they don't.

You are correct that users should not be surprised. However, doing something like taking the whole of the hosts device tree and handing it over to a 3rd party container, is ~~bad~~surprising enough. Doing it with root access is still more surprising. Doing it with `--cap-add=all` is yet more surprising. Doing all this behind their back is not the same as 'not surprising them'.  

Surprise or disappointment really depends on what your expectations were.  
See PR #1981 for a workaround aimed at informing users of what is going on - hopefully that leads to informed expectations.

> The PR should conserve the current command parameters so that they're passed on as before.

Agreed this is an alternate implementation.
However it doesn't address the issues identified with the Docker setup. 

Are the `build` or `test` broken when run with Docker?

**Comment by gc-plp** [comment]
> The fact that Docker silently runs a process as root

This does not necessarily need to happen. In order to launch `devtool`, you either [add your user to the `docker` group](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#appendix-b-setting-up-docker) or run the command as `sudo`. Both options are done voluntarily.

> handing it over to a 3rd party container

Are you referring to the fact that the container is built by someone else?

This container is actually built, maintained and updated by the Firecracker team, with the `Dockerfile` available [here](https://github.com/firecracker-microvm/firecracker/blob/master/tools/devctr).

> Are the `build` or `test` broken when run with Docker?

I just tested it and `devtool build` works fine, but `devtool test` needs to be launched with `sudo` rights, because the jailer creates cgroups when running tests.

`devtool shell` does not seem to launch a shell.

Adding Podman is a good idea, but we should be cautious when introducing changes in how people work with the updated components.

I would also talk about being able to run Podman as an alternative to Docker in the quickstart guide.

**Comment by bbros-dev** [comment]
> Are you referring to the fact that the container is built by someone else?

Correct.

> `devtool test` needs to be launched with `sudo` rights

Correct. As indicated, this PR does not address the minimal set of capabilities needed to run the test suite.

> `devtool shell` does not seem to launch a shell.

My apologies. Update forthcoming.

**Comment by bbros-dev** [comment]
I believe I made the changes requested.

>... we should be cautious when introducing changes in how people work with the updated components.

Agreed.  Likewise we shouldn't assume users come to Firecracker with the existing team's setup and habits.  I've added comments to the docs addressing users with Docker configured as rootless. 

> I would also talk about being able to run Podman as an alternative to Docker in the quickstart guide.

I've added some more context.

**Comment by bbros-dev** [comment]
>... people onboarding to Firecracker that may stumble upon devtool issues

I don't see any issues other than for users who run their containers as non-root encountering scripts that assumed root was the default.    
Note **this includes Docker users** who have configured their system to run containers as non-root, and who may have organizational policies to prohibit running containers as root.  
Note in these organizations arranging for a security review for a 3rd party container to be run as root can take months. In my experience this container would likely not pass - there is no documentation on why each of the privileges is required.  The review would have to reverse engineer each test case, work out the related privilege to see what their security policy was and then investigate the libraries the test case code relied on.

> it would be good if the default engine is Docker, with Podman as a fallback for advanced users.

Sorry, we don't agree. We can't commit code that promotes a runtime whose default setup we consider a security risk over a runtime whose default is to run as the users privileges. 
To setup a sane and secure Docker you have to be a relatively advanced user:
- https://docs.docker.com/engine/security/rootless/

We can't spend more time on this.  Feel free to amend or reject as you see fit - we don't take these things personally ;)

**Comment by bbros-dev** [comment]
Closing as 'fixed for us`, and we believe the following is workable for anyone else.

Anyone else who want this changed setup can apply the patch then:

```bash
git update-index --assume-unchanged tools/devtool
```

**Pull request closed without merging**
