### PR TITLE
Cleaning up create_fdt 

### PR DESCRIPTION
**Pull request by jackabald**
## Changes
Adds fdt to guest memory at the location `create_fdt` is called not in `create_fdt`.
Removes unnecessary `std::hash::BuildHasher` parameterization.
...

## Reason
@roypat we are not able to remove the `GuestMemoryMmap` parameter because we use it to create the memory node.
However, this updated code now writes the fdt to guest memory at the site of the caller utilizing the previously unused return value from `create_fdt`. 
- separation of concerns
- simplify unit testing
#4700 

...

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this
  PR.
- [x] API changes follow the [Runbook for Firecracker API changes][2].
- [x] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [x] New `TODO`s link to an issue.
- [x] Commits meet
  [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

______________________________________________________________________

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by roypat** [comment]
> we are not able to remove the GuestMemoryMmap parameter because we use it to create the memory node.

ah, rip, I missed that. Oh well, this is still an improvement :D Could you have a look at fixing the compilation errors/warnings, though? :o

**Comment by roypat** [comment]
Hi @jackabald,
did you have a chance to look at this again yet?

**Comment by ShadowCurse** [comment]
Hi @jackabald, are you still working on this?

**Comment by jackabald** [comment]
hey @ShadowCurse , sorry haven't looked at this in a bit. I am having troubles finding why the build is failing. If you could take a look that would be great!

**Comment by ShadowCurse** [comment]
So the issue is in the absence of `GuestAddress` import in the `src/vmm/src/arch/aarch64/fdt.rs`. Basically you need to drop last commit that reverts addition of this import.
Also can you please rebase this PR on top of main and squash rest of your commits?

**Review by roypat — APPROVED** [review]

**Comment by roypat** [comment]
Hi @jackabald,
I've gone ahead and fixed the small import issue, so we can go ahead with merging this. Thanks again for your contribution!

**Review by ShadowCurse — APPROVED** [review]

**Pull request merged**
