### PR TITLE
fix AMD boot warning

### PR DESCRIPTION
**Pull request by serban300**
Issue #, if available: #814 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by serban300** [comment]
I decreased the coverage since there is no point in testing a method by duplicating the code.

**Comment by andreeaflorescu** [comment]
@serban300 you can add a new unit test for something that is not yet testing (and it doesn't have to be related to this PR). Our goal should always be to increase the coverage.

**Comment by serban300** [comment]
> @serban300 you can add a new unit test for something that is not yet testing (and it doesn't have to be related to this PR). Our goal should always be to increase the coverage.

I see how this could help but I don't like it as s solution. I think that exceptionally, if we're in a situation where unit tests don't make sense we should be ready to accept a small decrease in coverage.

Anyway, I added a test that duplicates the code for the moment, just to keep the coverage. If you have any suggestions on where I could add a new unit test instead ( for something that is not yet tested ), I can do it.

**Comment by aghecenco** [comment]
>  If you have any suggestions on where I could add a new unit test instead ( for something that is not yet tested ), I can do it.

Jumping in because I recently found myself in this predicament :smile: You can generate the coverage report and pick whatever you like from the files that have < 100% coverage.

```bash
sudo env PATH=$PATH cargo kcov --all -- --exclude-pattern=${CARGO_HOME:-$HOME/.cargo/},build/,tests/,usr/lib/gcc,lib/x86_64-linux-gnu/,pnet,bootparam.rs,elf.rs,mpspec.rs,msr_index.rs,_gen --exclude-region='mod tests {'
```

In this particular case, looks like errors (and especially derived traits such as `Debug`) are not covered in the `cpuid` crate; this PR touches code in the same crate, so it wouldn't be entirely unrelated if you added tests for the `Debug` trait. And you can always derive - and test - `Display`, especially if the error is propagated all the way to the user.

**Comment by serban300** [comment]
Thanks for jumping in ! The indications on how to generate the coverage report were very useful. 

I would leave the PR as it is for the moment. I think that testing Debug or Display is almost the same as having tests that duplicate the code.

**Pull request merged**
