### PR TITLE
Update all error structs/enums to use thiserror::Error

### LINKED ISSUE #3278: Update all error structs/enums to use `thiserror::Error`
Currently most error enums in Firecracker use `thiserror::Error` to automatically implement `Error` and `Display` and `From` traits. 
But there are some that still don't use `thiserror` and have 50+ lines of implementations of `Display` trait or use `derive_more::From`

The goal of this issue is to make all Error structs/enums in Firecracker uniform.

### PR DESCRIPTION
**Pull request by cm-iwata**
## Changes

This PR is a continuation of #3637 by @sri-srikanth.
Fixed VMM package enums and structs to use thiserror.

## Reason

I believe this PR will close #3278.
```bash
$ grep "Display.*for.*Error" -r src/  | wc -l
0
```

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by cm-iwata** [comment]
DCO check failed.
https://github.com/firecracker-microvm/firecracker/pull/3996/checks?check_run_id=15458514824

The author of this commit is @takakoutso, but it was signed by @sri-srikanth. How can I fix the commit message?
https://github.com/firecracker-microvm/firecracker/pull/3637/commits/b1b0573d0874a76936f6ec392b814f56a53e29cd

**Comment by cm-iwata** [comment]
If the review is OK, I plan to do the following work
* Adjust coverage
* squash commits and add Co-authored-by
    * [This commit](https://github.com/firecracker-microvm/firecracker/pull/3996/commits/ffa6632fb8dcbf211787537cedf4dac54c544754) doesn't pass gitlint tests, but I plan to squash this commit, so I'm just using the commit by sri-srikanth

**Comment by ShadowCurse** [comment]
I think you can squash all commits and add @takakoutso  and  @sri-srikanth as co-authors when you edit the commit message.

**Comment by roypat** [comment]
Could you also remove https://github.com/firecracker-microvm/firecracker/blob/24adb76b907eb6b2690d5a4da1ced7cdd84d72f5/src/vmm/src/builder.rs#L1607-L1653 as part of this, please?

**Comment by cm-iwata** [comment]
> Could you also remove
> as part of this, please?

Deleted!

**Comment by roypat** [comment]
> > Could you also remove
> > as part of this, please?
> 
> Deleted!

Thanks. I think the gitlint failure is the only thing left, and this looks good to go!

**Comment by cm-iwata** [comment]
@roypat 
> Thanks. I think the gitlint failure is the only thing left, and this looks good to go!

Is it okay to squash and re-push these commits now?
Should I wait until this PR is approved?

**Comment by ShadowCurse** [comment]
Yes, you need to squash commits first, then PR can be approved.

**Comment by cm-iwata** [comment]
@ShadowCurse 
> Yes, you need to squash commits first, then PR can be approved.

I have squashed these commits and pushed them again.
Would you be able to review this?

**Review by ShadowCurse — APPROVED** [review]

**Review by roypat — APPROVED** [review]

**Pull request merged**
