### PR TITLE
Refactoring of result and error types

### PR DESCRIPTION
**Pull request by ShadowCurse**
## Changes
Refactoring of result and error types. More info in commit messages.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by JonathanWoollett-Light — APPROVED** [review]

**Comment by JonathanWoollett-Light** [comment]
I added https://github.com/rust-lang/rust-clippy/issues/11101

**Review by pb8o — COMMENTED** [review]
Is there a clippy lint for this kind of thing?

**Comment by JonathanWoollett-Light** [comment]
@pb8o Not currently but I posted an issue for adding one https://github.com/rust-lang/rust-clippy/issues/11101.

**Comment by roypat** [comment]
> > pb8o@ Not currently but I posted an issue for adding one [rust-lang/rust-clippy#11101](https://github.com/rust-lang/rust-clippy/issues/11101).
> 
> What about the other pattern? `Result<()>` Looks like https://rust-lang.github.io/rust-clippy/master/index.html#/result_unit_err is pretty close?

`Result<()>` is generally a type alias for `Result<(), Error>`. The `result_unit_err` lint is warnings against `Result<T, ()>`. The former (`Result<()>`)  is a pretty common pattern if all Results in a module use the same error type, in which case the top of the module will have some sort of `type Result<T> = std::result::Result<T, ModuleError>`. Compared to, say, Java, a function returning `Result<(), std::io::Error>` would be `void func() throws IOException`, e.g. there's no return value of interest, but errors can still occur.

**Review by sudanl0 — APPROVED** [review]

**Pull request merged**
