### PR TITLE
Make virtio flush disabled by default

### PR DESCRIPTION
**Pull request by pclesr**
## Reason for This PR

The existing implementation incorrectly advertises VIRTIO_BLK_T_FLUSH, when it
does not actually flush data to media from the host page cache. Unfortunately,
making all devices respect the flush feature bit slows down booting because
on a RW root partition, there can be a number of flush requests during the boot
process.

## Description of Changes

This commit adds a drive option 'want_flush' that allows each
drive to specify whether they require consistency and are willing
to take the performance hit of syncing data out to media. The
default is the existing behaviour, namely no flush.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by pclesr** [comment]
Are there any known issues with snapshots on AMD ?
`FAILED    integration_tests/functional/test_snapshot_basic.py::test_5_full_snapshots
` 
This test times out on AMD but passes on x86

**Comment by alindima** [comment]
> Are there any known issues with snapshots on AMD ?
> `FAILED integration_tests/functional/test_snapshot_basic.py::test_5_full_snapshots ` 
> This test times out on AMD but passes on x86

This shouldn't normally happen. I will log an issue and I will retrigger the AMD CI run for this PR.

**Comment by pclesr** [comment]
> > Are there any known issues with snapshots on AMD ?
> > `FAILED integration_tests/functional/test_snapshot_basic.py::test_5_full_snapshots ` 
> > This test times out on AMD but passes on x86
> 
> This shouldn't normally happen. I logged [this](https://github.com/firecracker-microvm/firecracker/issues/2232) issue and retriggered the CI run.

Thank you @alindima  -- the test worked on the second attempt. If/When it happens again, how do I trigger a CI run?

**Comment by alindima** [comment]
> > > Are there any known issues with snapshots on AMD ?
> > > `FAILED integration_tests/functional/test_snapshot_basic.py::test_5_full_snapshots ` 
> > > This test times out on AMD but passes on x86
> > 
> > 
> > This shouldn't normally happen. I logged [this](https://github.com/firecracker-microvm/firecracker/issues/2232) issue and retriggered the CI run.
> 
> Thank you @alindima -- the test worked on the second attempt. If/When it happens again, how do I trigger a CI run?

The CI dashboard is not publicly accessible, we will take care of any retriggers that are blocking PR merges.

**Comment by alindima** [comment]
@pclesr thank you very much for all the hard work that went into the last couple of PRs.

We are still working on deciding what the right fix for this flush issue is. We will let you know as soon as we reach a conclusion.

**Comment by pclesr** [comment]
>We are still working on deciding what the right fix for this flush issue is. We will let you know as soon as we reach a conclusion.
Can you help me understand where (or what) the objections are centered on? I had hoped that this backward-compatible fix would be more acceptable, and it would help me to understand where the "pain points" are.

I work in the auto embedded space now, and there are some very good use cases for firecracker.

**Comment by alindima** [comment]
It seems to me that the reason for the binary size increase on ARM is natural. I think you should increase the allowed target by a little, in `test_binary_size.py`

**Comment by alindima** [comment]
> > We are still working on deciding what the right fix for this flush issue is. We will let you know as soon as we reach a conclusion.
> 
> Can you help me understand where (or what) the objections are centered on? I had hoped that this backward-compatible fix would be more acceptable, and it would help me to understand where the "pain points" are.
> 
> I work in the auto embedded space now, and there are some very good use cases for firecracker.

We are trying to first investigate the impact this issue has from a data integrity/corruption standpoint, before committing to a fix. We haven't yet identified a regression test for this issue, where the outcome is data corruption, not just the lack of actual `flush`es.

We really appreciate and thank you for the effort you've put in. The way I see it, there is still another alternative to the approach outlined in this PR: not advertising the flush capability to the guest driver at all.

Any work in identifying any visible impact on the lack of flush would be greatly appreciated.

It's great to hear that Firecracker can be put to good use in the embedded space as well 😄

**Comment by pclesr** [comment]
> We are trying to first investigate the impact this issue has from a data integrity/corruption standpoint, before committing to a fix. We haven't yet identified a regression test for this issue, where the outcome is data corruption, not just the lack of actual `flush`es.
> 
I tried to develop a deterministic test case that did not involve power-cycling the host, but still have not found a solution. My approach was to try and get the pages in the page cache to be dropped when dirty without flushing (think: echo 1 > /proc/sys/vm/drop_caches). Unfortunately, even with MADV_DONTNEED I still could not get a deterministic way to force dirty pages in the cache to just be discarded without flushing to backing store. 

The goal would be to write a file from the VM without sync (so the pages are just sitting in the page cache on the host), then drop the pages (without writing to backing store, simulating a power failure) and then re-read the data from media. If one writes a pattern (as can be done with fio), it would hopefully then result in a mismatch between what was written in the VM and what in on physical media.

So far, no luck yet in this approach, but I'm still looking at options.

**Comment by pclesr** [comment]
@alindima : I have been out for a week -- what is the status of this? What have you all decided with respect to how to handle this issue?

**Comment by acatangiu** [comment]
@pclesr we're currently validating options (one of which being the one proposed by you in this PR) with `firecracker` customers.
Unfortunately now is a busy time for many people and this process takes some time. We have meetings on this topic scheduled up to mid-december, so that's the earlieast decision ETA.

**Comment by pclesr** [comment]
Any status update?

**Comment by sandreim** [comment]
Hey @pclesr! We have made progress on the issue, but we did not reach a decision on what are all the usecases we want to support. We plan to restart work on this next week.

**Comment by pclesr** [comment]
If Amazon is not going to take any status, can they at least fix the API so that the device is correctly shown as not supporting flush?

**Comment by georgepisaltu** [comment]
Hi @pclesr,

We understand the importance of this issue and we apologize for not being able to provide an accurate timeline for scoping and fixing it. This was a miss on our part as we are trying to come up with a solution that supports your use case as well as our other customers’. 

We are actively working on this issue and our next steps are to align with our other customers with respect to the fix and then implementing it. For now, we will remove the flush virtio feature because, as you pointed out, it was not correct to offer it if we don’t implement it.

**Comment by georgepisaltu** [comment]
Hi @pclesr,

We reached a conclusion regarding this issue and we would like to add the option to configure the block device to use the right flushing mechanic, but by default it should be the same way it has been. This PR is a very good starting point and we'd like to resume progress here.

Thank you for your patience. Let us know if you are still willing to contribute to this PR. If so, we will start reviewing it and we can move forward from there.

**Comment by georgepisaltu** [comment]
I went ahead and implemented the required changes, see the PR [here](https://github.com/firecracker-microvm/firecracker/pull/2447).

I will close this PR in favor of the other one.

**Pull request closed without merging**
