### PR TITLE
doc: Tweak markdown formatting

### PR DESCRIPTION
**Pull request by jeffwidman**
## Changes

Tweak markdown formatting by adding ` around code.

## Reason

Tweak markdown formatting by adding ` around code.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] New `unsafe` code is documented.
- [x] API changes follow the [Runbook for Firecracker API changes][2].
- [x] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

---

- [ ] This functionality can be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md

### CODE REVIEW

**Comment by jeffwidman** [comment]
Given that this is just a docs formatting change, I'm unclear which of the PR checklist is considered to apply? Happy to do whatever is needed...

**Comment by JonathanWoollett-Light** [comment]
Looking at this PR I think you can tick all the boxes except:

> - [ ] This functionality can be added in [`rust-vmm`][1].

**Review by dianpopa — COMMENTED** [review]
You need to sign off your commit:
`git commit --amend -s`
I would also suggest modifying the commit so smth more suggestive:
```
doc: tweak formatting
```

**Review by dianpopa — APPROVED** [review]

**Review by luminitavoicu — DISMISSED** [review]

**Comment by jeffwidman** [comment]
Thanks, and sorry for the delay. Just rebased, signed the commit, and force-pushed. Also updated the PR description as requested.

**Comment by jeffwidman** [comment]
Anything else I need to do here?

**Review by dianpopa — APPROVED** [review]

**Review by luminitavoicu — APPROVED** [review]

**Pull request merged**
