### PR TITLE
Fix superseded advice about region choice for EC2 bare metal

### PR DESCRIPTION
**Pull request by sftim**
## Reason for This PR

Outdated information in [Setting up a Development Environment for Firecracker](https://github.com/firecracker-microvm/firecracker/blob/22908c9fb0cd5fb20febc5d18ff1284caa5f3a53/docs/dev-machine-setup.md#readme)

## Description of Changes

Replace cautionary note that AWS only provide bare-metal instances in one region; these are now more widely available.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Review by dianpopa — COMMENTED** [review]
Hello @sftim ,

Thanks a lot for contributing. Changes look good, however we need you to please:
* sign your commit: "git commit --amend -s"
* adjust the commit message to conform to the 50/72 rule. I d suggest:
```
doc: fix misleading advice in dev-machine-setup

Update statement regarding EC2 bare-metal region availability
to reflect current situation. 
```

**Comment by sftim** [comment]
It's already a signed commit, I hope. I'll amend the message.

**Comment by dianpopa** [comment]
> It's already a signed commit, I hope. I'll amend the message.

indeed, it s a verified commit. I was actually referring to inserting the "Signed-off by" signature in the commit.

**Review by dianpopa — APPROVED** [review]

**Review by georgepisaltu — DISMISSED** [review]

**Comment by sftim** [comment]
`Signed-off-by:` trailer added

**Review by dianpopa — APPROVED** [review]

**Review by georgepisaltu — APPROVED** [review]

**Pull request merged**
