### PR TITLE
Removed dup code from jailer/env/clone()

### PR DESCRIPTION
**Pull request by seafoodfry**
## Changes

Found duplicated code while reviewing the jailer.
There were no differences between the x86_64 and the aarch64 versions of the clone sys call.

## Reason

Cleanup

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this
  PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet
  [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

______________________________________________________________________

- [x] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by roypat** [comment]
Hi @seafoodfry, 
thank you for your PR! You're right that this code is indeed duplicated. There is a reason for this, namely that the order of the arguments to the clone syscall are different on x86_64 vs aarch64 [[1]]. Particularly, the final two arguments are `child_tid` and `tls`, with the x86_64 of the syscall having `child_tid` first, and the aarch64 version of the syscall having `tls` first. 

Now, Firecracker sets both of those arguments to `0`, so really, the order doesnt matter, and using a `cfg` to indicate this is quite overkill (and really, doesn't make the code any clearer either, imo. I remember being confused by this exactly thing around a year ago too when I stumbled across it!), so overall I agree with the change you propose. Could you add a code comment about the argument order thing? Just in case someone ever does try to use the `child_tid` and `tls` arguments, in which case the cfg would be actually needed.

[1]: https://man7.org/linux/man-pages/man2/clone.2.html#VERSIONS

**Comment by seafoodfry** [comment]
Thank you for your review @roypat !
Am new here but the explciit documentation there does sound like a great idea - super easy to forget that clone looks different in diff archs.
I went a bit verbose to leave an easy to find trail of how to make the code work for different platforms in case it was ever needed again.
ptal

**Review by roypat — DISMISSED** [review]
Thanks!

**Review by zulinx86 — APPROVED** [review]
@seafoodfry Thank you for your contribution! LGTM, but could you please fix styling issues to merge this?
- Make the line length <= 72 in commit message: https://buildkite.com/firecracker/firecracker-pr/builds/10303#0190b505-1bb0-49cd-b29d-fc603cda7f06/62-187
- Remove unneeded `return` statement: https://buildkite.com/firecracker/firecracker-pr/builds/10303#0190b505-1bb4-40fe-93b7-654df4eb0b32/8-360

**Comment by seafoodfry** [comment]
Done @roypat , and thank you for your patience while I learn the ropes here 🙏 
ptal

**Review by zulinx86 — APPROVED** [review]
Thank you for your contribution!! Looks good to me!

**Review by roypat — APPROVED** [review]
Apologies for the late review, I was on vacation last week. Everything looks good to me, thanks for this!!

**Pull request merged**
