### PR TITLE
Api server thread clean shutdown

### PR DESCRIPTION
**Pull request by acatangiu**
## Changes

Use dedicated kill switch mechanism to break out of micro-http loop and gracefully shutdown the API server thread.

Remove hacky "/shutdown-internal" HTTP request which was externally exposing a way to bring down parts of firecracker components.

## Dependencies

Ideally needs https://github.com/firecracker-microvm/micro-http/pull/33 merged first, then point the dependency there.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] ~If a specific issue led to this PR, this PR closes the issue.~
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] ~New `unsafe` code is documented.~
- [x] ~API changes follow the [Runbook for Firecracker API changes][2].~
- [x] ~User-facing changes are mentioned in `CHANGELOG.md`.~
- [x] All added/changed functionality is tested.
- [x] ~New `TODO`s link to an issue.~

---

- [x] ~This functionality can be added in [`rust-vmm`][1].~

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md

### CODE REVIEW

**Comment by JonathanWoollett-Light** [comment]
Thank you for the contribution, looks like a good change.

**Comment by xmarcalx** [comment]
Hi @acatangiu ,

Thank you very much for your contribution and sorry for the late turnaround. 
The PR needs to be rebased and @ShadowCurse  will perform the review.

**Comment by ShadowCurse** [comment]
Hi @acatangiu do you want to rebase this PR on top of main or do you want me to do that?

**Comment by acatangiu** [comment]
> Hi @acatangiu do you want to rebase this PR on top of main or do you want me to do that?

Yes, feel free to do it, thank you!

**Review by sudanl0 — APPROVED** [review]

**Review by JonathanWoollett-Light — CHANGES_REQUESTED** [review]
It is not clear to me why we need `try_connect`, what is the problem with using `UnixStream::connect` where we used it originally?

**Comment by ShadowCurse** [comment]
@JonathanWoollett-Light I did not change the PR. I just rebased it on top of main and fixed merge conflicts.
Considerring `try_connect` is only used in one test, I will remove it.

**Comment by acatangiu** [comment]
> @ShadowCurse It is not clear to me why we need `try_connect`, what is the problem with using `UnixStream::connect` where we used it originally?

Iirc I added this “try_connect” just for tests to make sure tests don’t sporadically fail based on different thread scheduling on different machines. At some point I know for sure tests would sporadically fail when test thread tried to connect to api thread before api thread had the chance to create the socket.

Not sure if this is still a problem anymore, but I would still keep “try_connect” as defensive programming.

**Review by JonathanWoollett-Light — APPROVED** [review]
lgtm

**Review by sudanl0 — APPROVED** [review]

**Pull request merged**
