### PR TITLE
jailer: Handle cgroups v2 mounts

### PR DESCRIPTION
**Pull request by acipu-aws**
Issue #, if available: #841 

Description of changes: The previous version of the jailer only handled cgroups v1. The current
implementation also handles v2, but still gives priority to v1 (e.g. if
a cgroups v1 mount point that matches a controller is found, that one is
used)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Signed-off-by: Andrei Cipu <acipu@amazon.com>

### CODE REVIEW

**Comment by dhrgit** [comment]
@acipu-aws Why are you updating `Cargo.lock` here? Can you resolve the conflicts and resubmit, please? It'd probably be easiest to revert the lock.

**Comment by acipu-aws** [comment]
> @acipu-aws Why are you updating `Cargo.lock` here? Can you resolve the conflicts and resubmit, please? It'd probably be easiest to revert the lock.

I need it in order to add lazy-static as a dependency. It was automatically updated during build.

**Comment by aghecenco** [comment]
We customarily only update `Cargo.lock` at every release. The change in `Cargo.toml` is enough to pull in the new dependency.

**Comment by acipu-aws** [comment]
Understood. Will remove it and resubmit.

**Comment by andreeaflorescu** [comment]
@alexandruag please take a look at this PR.

**Comment by acipu-aws** [comment]
@alexandruag , could you please take a look?

**Comment by dianpopa** [comment]
Closing this for now. Feel free to reopen if work needs to/can be resumed on this.

**Pull request closed without merging**
