### PR TITLE
chore: update base64 dependency from 0.13.0 to 0.21.0

### PR DESCRIPTION
**Pull request by roypat**
It seems that dependabot is not monitoring our library crate .toml files, as our top-level Cargo.toml only specifies the binary crates as workspace members. Note that this is the only dependency update we've missed, as for minor and patch versions we get them through `Cargo.lock` updates (which dependabot does independently of how a dependency is pulled in)

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by zulinx86 — COMMENTED** [review]
Do we have a long-term solution to avoid this type of dependency update issues?

**Comment by JonathanWoollett-Light** [comment]
> > Do we have a long-term solution to avoid this type of dependency update issues?
> 
> We can either add all our crates to the `workspace` list in `Cargo.toml`, or just wait until we're done merging everything so that only binary crates remain

I agree with this. We should remove `default_members` and just have `members` with everything in it.

**Comment by zulinx86** [comment]
> > > Do we have a long-term solution to avoid this type of dependency update issues?
> > 
> > 
> > We can either add all our crates to the `workspace` list in `Cargo.toml`, or just wait until we're done merging everything so that only binary crates remain
> 
> I agree with this. We should remove `default-members` and just have `members` with everything in it.

Can we do it in this PR?

**Review by zulinx86 — APPROVED** [review]

**Comment by roypat** [comment]
> > > > Do we have a long-term solution to avoid this type of dependency update issues?
> > > 
> > > 
> > > We can either add all our crates to the `workspace` list in `Cargo.toml`, or just wait until we're done merging everything so that only binary crates remain
> > 
> > 
> > I agree with this. We should remove `default-members` and just have `members` with everything in it.
> 
> Can we do it in this PR?

Usually I'd be all over that, but I'm a bit apprehensious because I don't quite know _why_ these are set up the way they are. Let's not needlessly break things before a release :) I'll log an issue about it

**Pull request merged**
