### PR TITLE
tests: increase api timeouts from 100 to 200ms

### PR DESCRIPTION
**Pull request by danlemmond**
Issue #976 

Description of changes: Bumps the API Timeout from 100 to 200ms for all API calls during testing to avoid unnecessary vsock errors. This does increase the timeout for _all_ API calls, not just vsock, which should be noted.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
Occasionally it even goes up to 250. But we can merge this as we are blocking other PRs.

**Comment by andreeaflorescu** [comment]
Hey @danlemmond, can you please update the timeout to 300? This is blocking other PRs from being merged so it's a quite pressing issue.

**Comment by danlemmond** [comment]
Will bump to 300ms and amend the commit this evening.

**Comment by danlemmond** [comment]
Apologies for the force push, changed the commit title to reflect the bump to 300ms.

**Comment by andreeaflorescu** [comment]
Hmm, so apparently I did a wrong force push. Apologies for that. We need only the last commit. But I do not have permissions to push the rebase to your local master branch. Can you please sign the commit?

**Comment by andreeaflorescu** [comment]
```
From ffe47d29b79804962635d974c1582889bb8d96be Mon Sep 17 00:00:00 2001
From: Dan Lemmond <d.j.lemmond@gmail.com>
Date: Mon, 4 Mar 2019 22:09:24 -0800
Subject: [PATCH] tests: increase api timeouts from 100 to 300ms

---
 tests/framework/defs.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tests/framework/defs.py b/tests/framework/defs.py
index ea22b2a..e8ce32b 100644
--- a/tests/framework/defs.py
+++ b/tests/framework/defs.py
@@ -11,7 +11,7 @@ JAILER_BINARY_NAME = 'jailer'
 """Jailer's binary name."""
 JAILER_DEFAULT_CHROOT = '/srv/jailer'
 """The default location for the chroot."""
-MAX_API_CALL_DURATION_MS = 100
+MAX_API_CALL_DURATION_MS = 300
 """Maximum accepted duration of an API call, in milliseconds."""
 MICROVM_KERNEL_RELPATH = 'kernel/'
 """Relative path to the location of the kernel file."""
-- 
2.7.4

```

**Comment by danlemmond** [comment]
Commit should now be signed

**Comment by andreeaflorescu** [comment]
Hmm, did you updated this branch? Because I don't see any commits here yet.

**Comment by andreeaflorescu** [comment]
Also, the commit doesn't seem to be signed.

**Comment by andreeaflorescu** [comment]
To sign your commits you can use `git commit --amend --no-edit -s`.

**Pull request merged**
