### PR TITLE
[GuestMemory] import GuestMemoryRegion and GuestMemory traits from rust-vmm/vm-memory

### PR DESCRIPTION
**Pull request by serban300**
## Reason for This PR

addresses #1543 

## Description of Changes

We need this in order to align our interface to the `rust-vmm/vm-memory` interface. 

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided.
- [x] The description of changes is clear and encompassing.
- [x] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [x] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [x] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [x] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.
- [x] Either no new `unsafe` code has been added, or, the newly added `unsafe`
      code is unavoidable and properly documented.

### CODE REVIEW

**Comment by dianpopa** [comment]
The PRs on which this one depends are all merged now. You can go ahead and rebase.

**Comment by serban300** [comment]
> The PRs on which this one depends are all merged now. You can go ahead and rebase.

Thanks ! Done. Please take a look !

**Comment by andreeaflorescu** [comment]
@serban300 can you also make the corresponding changes so that crates depend on GuestMemory and not GuestMemoryMmap?

**Comment by serban300** [comment]
> @serban300 can you also make the corresponding changes so that crates depend on GuestMemory and not GuestMemoryMmap?

@andreeaflorescu there is a separate [issue](https://github.com/firecracker-microvm/firecracker/issues/1544) for this and I would like to implement it as part of a different PR or even a batch of PRs because it's not a blocker for the migration to `rust-vmm/vm-memory`.

I plan to do it as soon as possible, but I would prefer to work incrementally here. There will be a lot of changes and I would like these PRs to be as easy to review as possible.

**Comment by andreeaflorescu** [comment]
> > @serban300 can you also make the corresponding changes so that crates depend on GuestMemory and not GuestMemoryMmap?
> 
> @andreeaflorescu there is a separate [issue](https://github.com/firecracker-microvm/firecracker/issues/1544) for this and I would like to implement it as part of a different PR or even a batch of PRs because it's not a blocker for the migration to `rust-vmm/vm-memory`.
> 
> I plan to do it as soon as possible, but I would prefer to work incrementally here. There will be a lot of changes and I would like these PRs to be as easy to review as possible.

I actually find it harder to review because you miss the bigger picture and there are a lot of PRs that need to pass the tests. We then need to chase away all references of GuestMemoryMmap and replace them with GuestMemory.

**Comment by serban300** [comment]
> > > @serban300 can you also make the corresponding changes so that crates depend on GuestMemory and not GuestMemoryMmap?
> > 
> > 
> > @andreeaflorescu there is a separate [issue](https://github.com/firecracker-microvm/firecracker/issues/1544) for this and I would like to implement it as part of a different PR or even a batch of PRs because it's not a blocker for the migration to `rust-vmm/vm-memory`.
> > I plan to do it as soon as possible, but I would prefer to work incrementally here. There will be a lot of changes and I would like these PRs to be as easy to review as possible.
> 
> I actually find it harder to review because you miss the bigger picture and there are a lot of PRs that need to pass the tests. We then need to chase away all references of GuestMemoryMmap and replace them with GuestMemory.

As I see it, It shouldn't be harder to review the following PRs. The bigger picture is quite simple and hard to miss. We now have a trait `GuestMemory` that has to be used instead of the concrete implementation. It's a best practice in computer science. And we would need to chase away all the references of `GuestMemoryMmap` and replace them with `GuestMemory` anyway, regardless of whether we do it now or later. 

The only problem is the size of the PRs. Personally I would find it very hard to review a PR containing everything at once. Also if we merge this PR first, we will be able to parallelize some work later. We will be able to continue the work for switching to the `vm-memory` crate, while also working on using to the `GuestMemory` trait in the same time.

**Pull request merged**
