### PR TITLE
fix todo: log virtio address

### PR DESCRIPTION
**Pull request by sladyn98**
## Changes

Resolves `TODO: log address` see https://github.com/firecracker-microvm/firecracker/issues/3273.

## Reason

Resolves TODO.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] API changes follow the [Runbook for Firecracker API changes][2].
- [x] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [x] New `TODO`s link to an issue.
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by sladyn98** [comment]
@roypat @JonathanWoollett-Light I fixed this in a new PR because the old PR kind of got messy with the signing of commits

**Comment by JonathanWoollett-Light** [comment]
I think the commit titled can be reworded, I would suggest something like;

> [fix: Log virtio address]((https://github.com/firecracker-microvm/firecracker/pull/3592/commits/63088fa8f3ea496c596715a47657daadd631a648))

**Comment by JonathanWoollett-Light** [comment]
@sladyn98  Could you please rebase and resolve merge conflicts.

**Comment by sladyn98** [comment]
@JonathanWoollett-Light Yeah sorry completely forgot about this : )

**Comment by sladyn98** [comment]
@JonathanWoollett-Light Changed commit name and resolved conflicts

**Comment by xmarcalx** [comment]
Hi @sladyn98 ,

This PR has still some style issue and not passing the PR. Are yous till interested in fix those issues and merge your changes?

**Pull request closed without merging**
