### PR TITLE
[1.2] criterion: trim down dependencies

### PR DESCRIPTION
**Pull request by dianpopa**
## Changes

Criterion offers opportunity to choose between
features and it does declare some dependencies
as being optional (like the rayon one) which we currently include even though we do not need to.
We actually do not need to include what criterion defines as default features.

## Reason

Fix vulnerability in crossbeam-channel.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by andreitraistaru — APPROVED** [review]

**Review by zulinx86 — APPROVED** [review]

**Comment by zulinx86** [comment]
@dianpopa `tests/integration_tests/performance/test_versioned_serialization_benchmark.py` is failing continuously. It seems that we need to backport this patch as well. https://github.com/firecracker-microvm/firecracker/commit/be934e63c25ea41bd160f636257ee7ce72855ecd

**Comment by roypat** [comment]
> @dianpopa `tests/integration_tests/performance/test_versioned_serialization_benchmark.py` is failing continuously on m6g.metal. It seems that we need to backport this patch as well. [be934e6](https://github.com/firecracker-microvm/firecracker/commit/be934e63c25ea41bd160f636257ee7ce72855ecd)

Mh, any idea why we didn't run into this issue earlier though? That commit is from February, and we've added commits to the 1.2 branch just fine in March.

**Comment by dianpopa** [comment]
> @dianpopa `tests/integration_tests/performance/test_versioned_serialization_benchmark.py` is failing continuously on m6g.metal. It seems that we need to backport this patch as well. [be934e6](https://github.com/firecracker-microvm/firecracker/commit/be934e63c25ea41bd160f636257ee7ce72855ecd)

Thanks Taka for this! Actually that commit cuts the perf numbers on deserialize benchmark in half...did we ever have that kind of improvement on m6g? I need to investigate into why this change was done, unfortunately there is no detail in the commit message which actually refers to adding missing baselines...

**Comment by dianpopa** [comment]
> > @dianpopa `tests/integration_tests/performance/test_versioned_serialization_benchmark.py` is failing continuously on m6g.metal. It seems that we need to backport this patch as well. [be934e6](https://github.com/firecracker-microvm/firecracker/commit/be934e63c25ea41bd160f636257ee7ce72855ecd)
> 
> Mh, any idea why we didn't run into this issue earlier though? That commit is from February, and we've added commits to the 1.2 branch just fine in March.

I spawned multiple instances of the the `test_serialization_benchmark`  in a BuildKite pipeline and the results are a mix of pass and fails. Seems that the peformance results vary between `0.37` and `0.57` for m6g. I expect the CI to pass after some tries. I will open an issue to investigate this separately.

**Review by roypat — APPROVED** [review]

**Review by zulinx86 — APPROVED** [review]

**Pull request merged**
