### PR TITLE
Probable typo

### PR DESCRIPTION
**Pull request by Zefool**
Might be wrong about this, but I believe this is what was meant here.

### CODE REVIEW

**Comment by Zefool** [comment]
@dianpopa 
You assigned me, is there anything I need/can do here right now?

**Comment by dianpopa** [comment]
> Might be wrong about this, but I believe this is what was meant here.

Hi @Zefool , it is not a typo. Look for "Speculation_Store_Bypass" in the kernel file [fs/proc/array.c](https://github.com/torvalds/linux/blob/v4.17/fs/proc/array.c#L333) and check out the possible `case` values that it can have .

**Comment by acatangiu** [comment]
@Zefool closing this PR, but thanks and keep'em coming! 👍

**Comment by Zefool** [comment]
Awesome, thanks

**Pull request closed without merging**
