### PR TITLE
bump vm-memory dependency to 0.7.0

### PR DESCRIPTION
**Pull request by alindima**
# Reason for This PR

There is a new minor version for vm-memory and we already consume it in the io_uring crate.
This PR unifies the versions

## Description of Changes

`[Author TODO: add description of changes.]`

- [ ] This functionality can be added in [`rust-vmm`][1].

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The issue which led to this PR has a clear conclusion.
- [ ] This PR follows the solution outlined in the related issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any newly added `unsafe` code is properly documented.
- [ ] Any API changes follow the [Runbook for Firecracker API changes][2].
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

[1]: https://github.com/rust-vmm
[2]: ../docs/api-change-runbook.md

### CODE REVIEW

**Comment by dianpopa** [comment]
Why do not we do [this](https://github.com/alindima/firecracker/blob/main/src/io_uring/Cargo.toml#L11) `vm-memory = { path = "../vm-memory" }` for the `io_uring` crate also?

**Review by luminitavoicu — DISMISSED** [review]

**Comment by alindima** [comment]
> Why do not we do `vm-memory = { path = "../vm-memory" }` for the `io_uring` crate also?

Because we don't need to parametrise MmapRegion with an AtomicBitmap.
In vm-memory local crate we export an MmapRegion which is actually: `UpstreamMmapRegion<Option<AtomicBitmap>>;` (for dirty page tracking)

**Comment by raduiliescu** [comment]
> 

But isn't io_uring just a back-end implementation?  While I don't know the details something seems a bit fishy.

**Comment by alindima** [comment]
> But isn't io_uring just a back-end implementation? While I don't know the details something seems a bit fishy.

It is, but the io_uring crate has a dependency on vm-memory because it uses `MmapRegion` for mapping the rings and the `Bytes` and `VolatileSlice` abstractions for reading and writing to it. What exactly doesn't seem right?

**Review by serban300 — APPROVED** [review]

**Comment by alindima** [comment]
Closing in favour of: https://github.com/firecracker-microvm/firecracker/pull/2843 since that was the first PR

**Pull request closed without merging**
