### PR TITLE
[GuestMemory] rename to GuestMemoryMmap

### PR DESCRIPTION
**Pull request by serban300**
Signed-off-by: Serban Iorga <seriorga@amazon.com>

## Reason for This PR

partially addresses #1543 

## Description of Changes

Rename GuestMemory to GuestMemoryMmap

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] This PR is linked to an issue.
- [x] The description of changes is clear and encompassing.
- [x] No docs need to be updated as part of this PR.
- [x] Node-level documentation for touched code is included in this PR.
- [x] No API changes are included in this PR.
- [x] The changes in this PR have no user impact.
- [x] No new `unsafe` code has been added.

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
@serban300 most of these renames will need to be reverted once we switch to vm-memory because we will want crates to take a dependency on the GuestMemory trait and not the mmap implementation. Crates that take dependency on vm-memory should only be using the trait.

**Comment by andreeaflorescu** [comment]
> > @serban300 most of these renames will need to be reverted once we switch to vm-memory because we will want crates to take a dependency on the GuestMemory trait and not the mmap implementation. Crates that take dependency on vm-memory should only be using the trait.
> 
> Yes, but I would suggest to migrate like this and then do those changes incrementally as part of another item.

What would be the benefit in doing that?

**Comment by serban300** [comment]
> > > @serban300 most of these renames will need to be reverted once we switch to vm-memory because we will want crates to take a dependency on the GuestMemory trait and not the mmap implementation. Crates that take dependency on vm-memory should only be using the trait.
> > 
> > 
> > Yes, but I would suggest to migrate like this and then do those changes incrementally as part of another item.
> 
> What would be the benefit in doing that?

I don't see any disadvantage. It has to be done anyway, even if we import the `GuestMemory` trait. And we don't need more than this in order to migrate to `vm-memory`. But actually I can try to import the `GuestMemory` trait as part of this issue. Let me see how much work it would imply.

**Comment by serban300** [comment]
> > > > @serban300 most of these renames will need to be reverted once we switch to vm-memory because we will want crates to take a dependency on the GuestMemory trait and not the mmap implementation. Crates that take dependency on vm-memory should only be using the trait.
> > > 
> > > 
> > > Yes, but I would suggest to migrate like this and then do those changes incrementally as part of another item.
> > 
> > 
> > What would be the benefit in doing that?
> 
> I don't see any disadvantage. It has to be done anyway, even if we import the `GuestMemory` trait. And we don't need more than this in order to migrate to `vm-memory`. But actually I can try to import the `GuestMemory` trait as part of this issue. Let me see how much work it would imply.

@andreeaflorescu I tried to import the `GuestMemory` trait from `rust-vmm/vm-memory`. Here is the [PR](https://github.com/firecracker-microvm/firecracker/pull/1545) for that. Considering that that PR can't be merged yet since it depends on other PRs, considering that we need to rename the `GuestMemory` struct to `GuestMemoryMmap` anyway in order to be able to import the `GuestMemory` trait and considering that the renaming consists of a lot of small changes that touch a lot of code and that can lead to merge conflicts fairly easily, I propose the following strategy:

1. Merging this PR
2. Waiting for #1495 and #1497 to be merged
3. Merging #1545 

4. Implementing #1544 in a separate PR since
- it's not a blocker for the migration to `rust-vmm/vm-memory`
- it will contain fairly big changes that will touch a lot of code

**Pull request merged**
