### PR TITLE
fix: uses thiserror:Error in 12 more files in vmm

### PR DESCRIPTION
**Pull request by sri-srikanth**
## Changes

We updated numerous enums to utilize thiserror:Error instead of using impl std::fmt::Display for Error.

## Reason

This PR will fix part of Issue #3278 

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [X] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [X] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by JonathanWoollett-Light** [comment]
Can you please:
1. Squash [started migrating Display impl error messages into thiserror:Error fo…](https://github.com/firecracker-microvm/firecracker/pull/3637/commits/f7f4e1298228c5d1772d290e2f108001a739ba40) with [fixed error string formatting, removed impl for std::error declaratio…](https://github.com/firecracker-microvm/firecracker/pull/3637/commits/d7fab37300c0d5111b9cfc3d7b3f9cbcdee54b42)
2. Squash [converted Display implementations for errors to thiserror::Error for …](https://github.com/firecracker-microvm/firecracker/pull/3637/commits/aec9890d06b48bc1a9eaf7d6599b4529839d21f2) with [removed commented out code](https://github.com/firecracker-microvm/firecracker/pull/3637/commits/065534c12b855db03e1d3a20a5aa258eba928b5e)

**Comment by cm-iwata** [comment]
@sri-srikanth 
CC: @JonathanWoollett-Light 

How is the progress of this pull request?
I was not aware that you were working on this issue, so I was also making similar changes in the following branch.

https://github.com/cm-iwata/firecracker/commits/vmm-thiserror

If you don't have plans to continue the work further, would it be acceptable to merge my implemented unit tests into your branch and take over the task?

**Comment by ShadowCurse** [comment]
Hi @sri-srikanth, are you still working on this? 
If not maybe @cm-iwata do you want to take ownership of this one?

**Comment by cm-iwata** [comment]
> If not maybe @cm-iwata do you want to take ownership of this one?

Yes!
If he doesn't do any further work, I would like to take ownership.

**Comment by ShadowCurse** [comment]
Alright, @cm-iwata you are good to go then. As a mentioned before, please keep @sri-srikanth as a coauthor.

**Comment by cm-iwata** [comment]
@ShadowCurse
I created a new PR #3996.
Because I don't have permission push to sri-srikanth's branch

**Comment by roypat** [comment]
I am closing this as superseded by #3996. Thank you for your work on this issue @sri-srikanth!

**Pull request closed without merging**
